@echo off
echo Cleaning...
if exist manar01 rmdir /s /q manar01
echo Creating dir...
mkdir manar01
echo Copying...
xcopy "c:\Users\asus\my\almadrasah\build\web\*.*" "c:\Users\asus\my\almadrasah\manar01" /s /e /y /i
echo Listing...
dir manar01
