// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASc4Fpc1aKpHJuVUtLF_t_UG2tTPMVnQI',
    appId: '1:979291699789:ios:644e28ca79399fa11b7a04',
    messagingSenderId: '979291699789',
    projectId: 'etisak-784d6',
    storageBucket: 'etisak-784d6.firebasestorage.app',
    iosBundleId: 'com.almohawed.manar',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApXj1qxtyIH-9WTcRAZTs3feK2fN5FvPo',
    appId: '1:979291699789:android:71cbb69c0611e4411b7a04',
    messagingSenderId: '979291699789',
    projectId: 'etisak-784d6',
    storageBucket: 'etisak-784d6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyApXj1qxtyIH-9WTcRAZTs3feK2fN5FvPo', // Reusing Android API Key
    appId: '1:979291699789:web:f541d1ee0c65bd441b7a04',
    messagingSenderId: '979291699789',
    projectId: 'etisak-784d6',
    authDomain: 'etisak-784d6.firebaseapp.com',
    storageBucket: 'etisak-784d6.firebasestorage.app',
  );
}
