import pathlib

p = pathlib.Path('lib/src/features/wait_management/presentation/wait_management_screen.dart')
c = p.read_text(encoding='utf-8')

old = (
    "  // استيراد من الجدول العام\n"
    "  Future<void> _importFromGeneralSchedule() async {\n"
    "    if (_schoolId == null) return;\n"
    "    setState(() => _isLoading = true);\n"
    "    try {\n"
    "      final genSnap = await FirebaseFirestore.instance\n"
    "          .collection('Schools').doc(_schoolId)\n"
    "          .collection('GeneralSchedule')\n"
    "          .orderBy('createdAt', descending: true).limit(1).get();\n"
    "\n"
    "      if (genSnap.docs.isEmpty) {\n"
    "        _generateSchedule();\n"
    "        if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(\n"
    "          content: Text('لا يوجد جدول عام - تم التوليد التلقائي'),\n"
    "          backgroundColor: Color(0xFFD97706)));\n"
    "        return;\n"
    "      }\n"
    "\n"
    "      final data = genSnap.docs.first.data();\n"
    "      final teacherSchedules = data['teacherSchedules'] as Map<String, dynamic>? ?? {};\n"
    "\n"
    "      // استخراج حصص الانتظار من الجدول\n"
    "      // حصة الانتظار = حصة فارغة في جدول المعلم (لا يوجد فصل)\n"
    "      final waitByDayPeriod = <String, Map<int, List<String>>>{};\n"
    "      final waitNamesByDayPeriod = <String, Map<int, List<String>>>{};\n"
    "\n"
    "      for (final entry in teacherSchedules.entries) {\n"
    "        final teacherName = entry.key;\n"
    "        final teacherLessons = entry.value;\n"
    "        if (teacherLessons is! List) continue;\n"
    "\n"
    "        // ابحث عن حصص الانتظار (subject يحتوي 'منتظر' او 'انتظار')\n"
    "        for (final lesson in teacherLessons) {\n"
    "          if (lesson is! Map) continue;\n"
    "          final subject = (lesson['subject'] ?? '').toString();\n"
    "          final day = (lesson['dayName'] ?? lesson['day'] ?? '').toString();\n"
    "          final period = lesson['period'] as int? ?? 0;\n"
    "          if (subject.contains('منتظر') || subject.contains('انتظار') || subject.contains('نوبة')) {\n"
    "            waitByDayPeriod.putIfAbsent(day, () => {});\n"
    "            waitByDayPeriod[day]!.putIfAbsent(period, () => []);\n"
    "            waitByDayPeriod[day]![period]!.add(teacherName);\n"
    "            waitNamesByDayPeriod.putIfAbsent(day, () => {});\n"
    "            waitNamesByDayPeriod[day]!.putIfAbsent(period, () => []);\n"
    "            waitNamesByDayPeriod[day]![period]!.add(teacherName);\n"
    "          }\n"
    "        }\n"
    "      }\n"
    "\n"
    "      if (waitByDayPeriod.isEmpty) {\n"
    "        _generateSchedule();\n"
    "        if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(\n"
    "          content: Text('لا توجد حصص انتظار في الجدول - تم التوليد التلقائي'),\n"
    "          backgroundColor: Color(0xFFD97706)));\n"
    "        return;\n"
    "      }\n"
    "\n"
    "      // بناء الجدول من البيانات المستوردة\n"
    "      _schedule = {};\n"
    "      for (final day in waitByDayPeriod.keys) {\n"
    "        _schedule[day] = {};\n"
    "        for (final period in waitByDayPeriod[day]!.keys) {\n"
    "          final ids = waitByDayPeriod[day]![period]!;\n"
    "          final names = waitNamesByDayPeriod[day]![period]!;\n"
    "          _schedule[day]![period] = _Slot(\n"
    "            day: day, period: period,\n"
    "            teacherIds: ids.take(_waitCount).toList(),\n"
    "            teacherNames: names.take(_waitCount).toList(),\n"
    "          );\n"
    "        }\n"
    "      }\n"
    "\n"
    "      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(\n"
    "        content: Text('تم استيراد جدول الانتظار من الجدول العام'),\n"
    "        backgroundColor: Color(0xFF059669)));\n"
    "    } catch (e) {\n"
    "      _generateSchedule();\n"
    "    } finally {\n"
    "      if (mounted) setState(() => _isLoading = false);\n"
    "    }\n"
    "  }"
)

new = (
    "  // استيراد من TeacherSchedules (المصدر الصحيح)\n"
    "  Future<void> _importFromGeneralSchedule() async {\n"
    "    if (_schoolId == null) return;\n"
    "    setState(() => _isLoading = true);\n"
    "    try {\n"
    "      // جلب جداول المعلمين من TeacherSchedules\n"
    "      final tsSnap = await FirebaseFirestore.instance\n"
    "          .collection('Schools').doc(_schoolId)\n"
    "          .collection('TeacherSchedules').get();\n"
    "\n"
    "      // بناء خريطة teacherId -> teacherName\n"
    "      final teacherNameById = <String, String>{};\n"
    "      for (final t in _teachers) {\n"
    "        teacherNameById[t['id'] as String] = t['name'] as String;\n"
    "      }\n"
    "\n"
    "      // استخراج حصص الانتظار\n"
    "      // البنية: {day, period, subject: 'منتظر 1/2/3', teacherId}\n"
    "      // نجمع: لكل (day, period) -> قائمة المعلمين مرتبة حسب رقم المنتظر\n"
    "      final waitMap = <String, Map<int, Map<int, Map<String, String>>>>{};\n"
    "      // waitMap[day][period][waitNum] = {id, name}\n"
    "\n"
    "      for (final doc in tsSnap.docs) {\n"
    "        final teacherId = doc.id;\n"
    "        final teacherName = teacherNameById[teacherId] ?? '';\n"
    "        final slots = (doc.data()['slots'] as List?) ?? [];\n"
    "\n"
    "        for (final slot in slots) {\n"
    "          if (slot is! Map) continue;\n"
    "          final subject = (slot['subject'] ?? '').toString();\n"
    "          final day = (slot['day'] ?? slot['dayName'] ?? '').toString();\n"
    "          final period = (slot['period'] as num?)?.toInt() ?? 0;\n"
    "\n"
    "          if (!subject.contains('منتظر') && !subject.contains('انتظار') && !subject.contains('نوبة')) continue;\n"
    "          if (day.isEmpty || period == 0) continue;\n"
    "\n"
    "          // استخراج رقم المنتظر من الاسم (منتظر 1 -> 1, منتظر 2 -> 2)\n"
    "          int waitNum = 1;\n"
    "          final numMatch = RegExp(r'(\\d+)').firstMatch(subject);\n"
    "          if (numMatch != null) waitNum = int.tryParse(numMatch.group(1)!) ?? 1;\n"
    "\n"
    "          waitMap.putIfAbsent(day, () => {});\n"
    "          waitMap[day]!.putIfAbsent(period, () => {});\n"
    "          waitMap[day]![period]![waitNum] = {'id': teacherId, 'name': teacherName};\n"
    "        }\n"
    "      }\n"
    "\n"
    "      if (waitMap.isEmpty) {\n"
    "        // جرّب GeneralSchedule كبديل\n"
    "        final genSnap = await FirebaseFirestore.instance\n"
    "            .collection('Schools').doc(_schoolId)\n"
    "            .collection('GeneralSchedule')\n"
    "            .orderBy('createdAt', descending: true).limit(1).get();\n"
    "\n"
    "        if (!genSnap.docs.isEmpty) {\n"
    "          final data = genSnap.docs.first.data();\n"
    "          final teacherSchedules = data['teacherSchedules'] as Map<String, dynamic>? ?? {};\n"
    "          for (final entry in teacherSchedules.entries) {\n"
    "            final teacherName = entry.key;\n"
    "            final lessons = entry.value;\n"
    "            if (lessons is! List) continue;\n"
    "            for (final lesson in lessons) {\n"
    "              if (lesson is! Map) continue;\n"
    "              final subject = (lesson['subject'] ?? '').toString();\n"
    "              final day = (lesson['dayName'] ?? lesson['day'] ?? '').toString();\n"
    "              final period = (lesson['period'] as num?)?.toInt() ?? 0;\n"
    "              if (!subject.contains('منتظر') && !subject.contains('انتظار')) continue;\n"
    "              if (day.isEmpty || period == 0) continue;\n"
    "              int waitNum = 1;\n"
    "              final nm = RegExp(r'(\\d+)').firstMatch(subject);\n"
    "              if (nm != null) waitNum = int.tryParse(nm.group(1)!) ?? 1;\n"
    "              waitMap.putIfAbsent(day, () => {});\n"
    "              waitMap[day]!.putIfAbsent(period, () => {});\n"
    "              waitMap[day]![period]![waitNum] = {'id': '', 'name': teacherName};\n"
    "            }\n"
    "          }\n"
    "        }\n"
    "      }\n"
    "\n"
    "      if (waitMap.isEmpty) {\n"
    "        _generateSchedule();\n"
    "        if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(\n"
    "          content: Text('لا توجد حصص انتظار في الجدول - تم التوليد التلقائي'),\n"
    "          backgroundColor: Color(0xFFD97706), behavior: SnackBarBehavior.floating));\n"
    "        return;\n"
    "      }\n"
    "\n"
    "      // بناء الجدول\n"
    "      _schedule = {};\n"
    "      int importedCount = 0;\n"
    "      for (final day in waitMap.keys) {\n"
    "        _schedule[day] = {};\n"
    "        for (final period in waitMap[day]!.keys) {\n"
    "          final byNum = waitMap[day]![period]!;\n"
    "          final ids = <String>[];\n"
    "          final names = <String>[];\n"
    "          for (int i = 1; i <= _waitCount; i++) {\n"
    "            if (byNum.containsKey(i)) {\n"
    "              ids.add(byNum[i]!['id']!);\n"
    "              names.add(byNum[i]!['name']!);\n"
    "            }\n"
    "          }\n"
    "          if (ids.isNotEmpty) {\n"
    "            _schedule[day]![period] = _Slot(\n"
    "              day: day, period: period,\n"
    "              teacherIds: ids, teacherNames: names);\n"
    "            importedCount++;\n"
    "          }\n"
    "        }\n"
    "      }\n"
    "\n"
    "      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(\n"
    "        content: Text('تم استيراد $importedCount خانة انتظار من الجدول'),\n"
    "        backgroundColor: const Color(0xFF059669), behavior: SnackBarBehavior.floating));\n"
    "    } catch (e) {\n"
    "      debugPrint('import error: $e');\n"
    "      _generateSchedule();\n"
    "    } finally {\n"
    "      if (mounted) setState(() => _isLoading = false);\n"
    "    }\n"
    "  }"
)

if old in c:
    c = c.replace(old, new)
    print("Fixed import function")
else:
    print("Pattern not found - trying partial")
    idx = c.find("Future<void> _importFromGeneralSchedule()")
    print(f"Function at: {idx}")

p.write_text(c, encoding='utf-8')
print("Done")
