import pathlib
p = pathlib.Path('lib/src/features/schedule/presentation/excel_import_wizard.dart')
c = p.read_text(encoding='utf-8')

dart = (
    "\n"
    "  // ─── STEP 1: Upload ──────────────────────────────────────────────────────\n"
    "  Widget _buildUploadStep() {\n"
    "    return SingleChildScrollView(\n"
    "      padding: const EdgeInsets.all(32),\n"
    "      child: Column(children: [\n"
    "        const SizedBox(height: 8),\n"
    "        // Drop zone\n"
    "        GestureDetector(\n"
    "          onTap: _pickFile,\n"
    "          child: AnimatedBuilder(\n"
    "            animation: _pulseAnim,\n"
    "            builder: (_, __) => Container(\n"
    "              width: double.infinity, height: 180,\n"
    "              decoration: BoxDecoration(\n"
    "                color: _C.card,\n"
    "                borderRadius: BorderRadius.circular(20),\n"
    "                border: Border.all(\n"
    "                  color: _C.violet.withOpacity(0.3 + _pulseAnim.value * 0.2), width: 1.5,\n"
    "                  style: BorderStyle.solid),\n"
    "                boxShadow: [BoxShadow(color: _C.violet.withOpacity(_pulseAnim.value * 0.08), blurRadius: 30)],\n"
    "              ),\n"
    "              child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [\n"
    "                Container(\n"
    "                  width: 64, height: 64,\n"
    "                  decoration: BoxDecoration(\n"
    "                    gradient: LinearGradient(colors: [_C.violet.withOpacity(0.2), _C.sky.withOpacity(0.1)],\n"
    "                        begin: Alignment.topLeft, end: Alignment.bottomRight),\n"
    "                    shape: BoxShape.circle,\n"
    "                    border: Border.all(color: _C.violet.withOpacity(0.4)),\n"
    "                  ),\n"
    "                  child: const Icon(Icons.cloud_upload_rounded, color: _C.violetLt, size: 30),\n"
    "                ),\n"
    "                const SizedBox(height: 14),\n"
    "                const Text('اسحب الملف هنا أو اضغط للاختيار',\n"
    "                    style: TextStyle(color: _C.text, fontSize: 15, fontWeight: FontWeight.w600)),\n"
    "                const SizedBox(height: 6),\n"
    "                Text('يدعم .xlsx و .xls', style: TextStyle(color: _C.textMuted, fontSize: 12)),\n"
    "              ]),\n"
    "            ),\n"
    "          ),\n"
    "        ),\n"
    "        const SizedBox(height: 24),\n"
    "        // Format guide\n"
    "        Container(\n"
    "          padding: const EdgeInsets.all(18),\n"
    "          decoration: BoxDecoration(\n"
    "            color: _C.card,\n"
    "            borderRadius: BorderRadius.circular(16),\n"
    "            border: Border.all(color: _C.border),\n"
    "          ),\n"
    "          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "            Row(children: [\n"
    "              Container(width: 3, height: 16, decoration: BoxDecoration(color: _C.amber, borderRadius: BorderRadius.circular(2))),\n"
    "              const SizedBox(width: 8),\n"
    "              const Text('تنسيق الملف المطلوب', style: TextStyle(color: _C.text, fontWeight: FontWeight.bold, fontSize: 13)),\n"
    "            ]),\n"
    "            const SizedBox(height: 12),\n"
    "            _formatRow('1', 'الصف الأول', 'عناوين الأعمدة', _C.textMuted),\n"
    "            _formatRow('2', 'الصف الثاني', 'أسماء الأيام (الاحد، الاثنين...)', _C.sky),\n"
    "            _formatRow('3', 'الصف الثالث', 'أرقام الحصص (1، 2، 3...)', _C.amber),\n"
    "            _formatRow('4+', 'الصفوف التالية', 'اسم المعلم + بيانات الحصص', _C.emerald),\n"
    "          ]),\n"
    "        ),\n"
    "        const SizedBox(height: 24),\n"
    "        SizedBox(width: double.infinity, child: _primaryBtn('اختيار الملف', Icons.folder_open_rounded, _pickFile, _C.violet)),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  Widget _formatRow(String num, String label, String desc, Color color) {\n"
    "    return Padding(\n"
    "      padding: const EdgeInsets.only(bottom: 8),\n"
    "      child: Row(children: [\n"
    "        Container(\n"
    "          width: 24, height: 24,\n"
    "          decoration: BoxDecoration(color: color.withOpacity(0.15), shape: BoxShape.circle,\n"
    "              border: Border.all(color: color.withOpacity(0.4))),\n"
    "          child: Center(child: Text(num, style: TextStyle(color: color, fontSize: 9, fontWeight: FontWeight.bold))),\n"
    "        ),\n"
    "        const SizedBox(width: 10),\n"
    "        Text(label, style: const TextStyle(color: _C.text, fontSize: 12, fontWeight: FontWeight.w500)),\n"
    "        const SizedBox(width: 6),\n"
    "        Text('— $desc', style: TextStyle(color: _C.textMuted, fontSize: 11)),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  // ─── STEP 2: Analyze ─────────────────────────────────────────────────────\n"
    "  Widget _buildAnalyzeStep() {\n"
    "    final total = _subjectStats.length;\n"
    "    return SingleChildScrollView(\n"
    "      padding: const EdgeInsets.all(24),\n"
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "        // File badge\n"
    "        Container(\n"
    "          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),\n"
    "          decoration: BoxDecoration(\n"
    "            color: _C.card, borderRadius: BorderRadius.circular(12),\n"
    "            border: Border.all(color: _C.border)),\n"
    "          child: Row(children: [\n"
    "            const Icon(Icons.insert_drive_file_rounded, color: _C.emerald, size: 18),\n"
    "            const SizedBox(width: 8),\n"
    "            Expanded(child: Text(_fileName, style: const TextStyle(color: _C.text, fontSize: 13), overflow: TextOverflow.ellipsis)),\n"
    "            Container(padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),\n"
    "              decoration: BoxDecoration(color: _C.emerald.withOpacity(0.15), borderRadius: BorderRadius.circular(20)),\n"
    "              child: const Text('تم التحليل', style: TextStyle(color: _C.emerald, fontSize: 10))),\n"
    "          ]),\n"
    "        ),\n"
    "        const SizedBox(height: 20),\n"
    "        // Stats row\n"
    "        Row(children: [\n"
    "          _glowStat(total.toString(), 'مادة مكتشفة', _C.sky, Icons.auto_awesome),\n"
    "          const SizedBox(width: 12),\n"
    "          _glowStat(_knownCount.toString(), 'معروفة', _C.emerald, Icons.check_circle_rounded),\n"
    "          const SizedBox(width: 12),\n"
    "          _glowStat(_unknownCount.toString(), 'تحتاج مراجعة',\n"
    "              _unknownCount > 0 ? _C.amber : _C.emerald, Icons.pending_rounded),\n"
    "        ]),\n"
    "        const SizedBox(height: 20),\n"
    "        Row(children: [\n"
    "          Container(width: 3, height: 14, decoration: BoxDecoration(color: _C.violet, borderRadius: BorderRadius.circular(2))),\n"
    "          const SizedBox(width: 8),\n"
    "          const Text('المواد المكتشفة', style: TextStyle(color: _C.text, fontWeight: FontWeight.bold, fontSize: 13)),\n"
    "        ]),\n"
    "        const SizedBox(height: 10),\n"
    "        ..._subjectStats.entries.map((e) => _subjectRow(e.key, SubjectMatcher.match(e.key), e.value)),\n"
    "        const SizedBox(height: 20),\n"
    "        SizedBox(width: double.infinity, child: _primaryBtn(\n"
    "          _reviewLessons.isEmpty ? 'متابعة للتأكيد' : 'مراجعة المواد غير المعروفة',\n"
    "          Icons.arrow_forward_rounded,\n"
    "          () => setState(() => _step = _reviewLessons.isEmpty ? ImportStep.confirm : ImportStep.review),\n"
    "          _C.violet)),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  Widget _glowStat(String value, String label, Color color, IconData icon) {\n"
    "    return Expanded(child: Container(\n"
    "      padding: const EdgeInsets.all(16),\n"
    "      decoration: BoxDecoration(\n"
    "        color: _C.card,\n"
    "        borderRadius: BorderRadius.circular(14),\n"
    "        border: Border.all(color: color.withOpacity(0.25)),\n"
    "        boxShadow: [BoxShadow(color: color.withOpacity(0.08), blurRadius: 20)],\n"
    "      ),\n"
    "      child: Column(children: [\n"
    "        Icon(icon, color: color, size: 20),\n"
    "        const SizedBox(height: 8),\n"
    "        Text(value, style: TextStyle(color: color, fontSize: 28, fontWeight: FontWeight.bold,\n"
    "            shadows: [Shadow(color: color.withOpacity(0.5), blurRadius: 8)])),\n"
    "        const SizedBox(height: 4),\n"
    "        Text(label, style: const TextStyle(color: _C.textMuted, fontSize: 10), textAlign: TextAlign.center),\n"
    "      ]),\n"
    "    ));\n"
    "  }\n"
    "\n"
    "  Widget _subjectRow(String raw, SubjectMatchResult result, int count) {\n"
    "    Color color; String badge; IconData icon;\n"
    "    if (result.confidence == MatchConfidence.high) { color = _C.emerald; badge = 'معروفة'; icon = Icons.check_circle_rounded; }\n"
    "    else if (result.confidence == MatchConfidence.medium) { color = _C.amber; badge = 'مقترحة'; icon = Icons.help_rounded; }\n"
    "    else { color = _C.rose; badge = 'غير معروفة'; icon = Icons.error_rounded; }\n"
    "    return Container(\n"
    "      margin: const EdgeInsets.only(bottom: 6),\n"
    "      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),\n"
    "      decoration: BoxDecoration(\n"
    "        color: _C.card,\n"
    "        borderRadius: BorderRadius.circular(10),\n"
    "        border: Border.all(color: color.withOpacity(0.15)),\n"
    "      ),\n"
    "      child: Row(children: [\n"
    "        Icon(icon, color: color, size: 15),\n"
    "        const SizedBox(width: 10),\n"
    "        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "          Text(raw, style: const TextStyle(color: _C.text, fontWeight: FontWeight.w600, fontSize: 13)),\n"
    "          if (result.matched != null)\n"
    "            Text('→ ' + result.matched!.officialName, style: TextStyle(color: color, fontSize: 11)),\n"
    "        ])),\n"
    "        Container(\n"
    "          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),\n"
    "          decoration: BoxDecoration(color: color.withOpacity(0.12), borderRadius: BorderRadius.circular(20)),\n"
    "          child: Text(badge, style: TextStyle(color: color, fontSize: 10, fontWeight: FontWeight.w600)),\n"
    "        ),\n"
    "        const SizedBox(width: 8),\n"
    "        Text(count.toString() + ' حصة', style: const TextStyle(color: _C.textMuted, fontSize: 10)),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
)

p.write_text(c + dart, encoding='utf-8')
print('part4 ok')
