import pathlib
p = pathlib.Path('lib/src/features/schedule/presentation/excel_import_wizard.dart')
c = p.read_text(encoding='utf-8')

dart = (
    "\n"
    "  Future<void> _pickFile() async {\n"
    "    setState(() => _isLoading = true);\n"
    "    try {\n"
    "      final result = await FilePicker.platform.pickFiles(\n"
    "          type: FileType.custom, allowedExtensions: ['xlsx', 'xls']);\n"
    "      if (result == null) { setState(() => _isLoading = false); return; }\n"
    "      final pf = result.files.first;\n"
    "      final bytes = kIsWeb ? pf.bytes! : (pf.bytes ?? await XFile(pf.path!).readAsBytes());\n"
    "      _workbook = excel.Excel.decodeBytes(bytes);\n"
    "      _fileName = pf.name;\n"
    "      setState(() { _isLoading = false; _step = ImportStep.analyze; });\n"
    "      await _analyzeFile();\n"
    "    } catch (e) {\n"
    "      setState(() => _isLoading = false);\n"
    "      _showError('فشل قراءة الملف');\n"
    "    }\n"
    "  }\n"
    "\n"
    "  Future<void> _analyzeFile() async {\n"
    "    if (_workbook == null) return;\n"
    "    setState(() => _isLoading = true);\n"
    "    try {\n"
    "      final sheetName = _workbook!.tables.keys.first;\n"
    "      final sheet = _workbook!.tables[sheetName]!;\n"
    "      if (sheet.rows.length < 3) { _showError('الملف لا يحتوي على بيانات كافية'); setState(() => _isLoading = false); return; }\n"
    "      final dayRow = sheet.rows[1];\n"
    "      final periodRow = sheet.rows[2];\n"
    "      final colInfo = <int, Map<String, dynamic>>{};\n"
    "      String currentDay = '';\n"
    "      for (var c = 1; c < dayRow.length; c++) {\n"
    "        final dv = dayRow[c]?.value?.toString().trim() ?? '';\n"
    "        if (_days.contains(dv)) currentDay = dv;\n"
    "        final pv = periodRow.length > c ? periodRow[c]?.value?.toString().trim() : null;\n"
    "        final period = int.tryParse(pv ?? '');\n"
    "        if (currentDay.isNotEmpty && period != null) colInfo[c] = {'day': currentDay, 'period': period};\n"
    "      }\n"
    "      final lessons = <ImportedLesson>[];\n"
    "      final rawSubjects = <String>{};\n"
    "      for (var r = 3; r < sheet.rows.length; r++) {\n"
    "        final row = sheet.rows[r];\n"
    "        if (row.isEmpty) continue;\n"
    "        final teacherName = row[0]?.value?.toString().trim() ?? '';\n"
    "        if (teacherName.isEmpty) continue;\n"
    "        for (var c = 1; c < row.length; c++) {\n"
    "          final info = colInfo[c]; if (info == null) continue;\n"
    "          final content = row[c]?.value?.toString().trim() ?? '';\n"
    "          if (content.isEmpty) continue;\n"
    "          String subject = content; String className = '';\n"
    "          if (content.contains('\\n')) { final pts = content.split('\\n'); className = pts[0].trim(); subject = pts.length > 1 ? pts[1].trim() : pts[0].trim(); }\n"
    "          else if (content.contains('-')) { final pts = content.split('-'); className = pts[0].trim(); subject = pts.length > 1 ? pts[1].trim() : pts[0].trim(); }\n"
    "          rawSubjects.add(subject);\n"
    "          final dayName = info['day'] as String;\n"
    "          final dayIndex = _days.indexOf(dayName);\n"
    "          lessons.add(ImportedLesson(teacherName: teacherName, rawSubject: subject,\n"
    "            matchResult: SubjectMatcher.match(subject), className: className,\n"
    "            dayName: dayName, dayIndex: dayIndex >= 0 ? dayIndex : 0, period: info['period'] as int));\n"
    "        }\n"
    "      }\n"
    "      _knownCount = rawSubjects.where((s) => !SubjectMatcher.match(s).needsReview).length;\n"
    "      _unknownCount = rawSubjects.where((s) => SubjectMatcher.match(s).needsReview).length;\n"
    "      _subjectStats = {};\n"
    "      for (final s in rawSubjects) { _subjectStats[s] = (_subjectStats[s] ?? 0) + 1; }\n"
    "      final reviewSubjects = rawSubjects.where((s) => SubjectMatcher.match(s).needsReview).toSet();\n"
    "      _reviewLessons = reviewSubjects.map((s) => lessons.firstWhere((l) => l.rawSubject == s)).toList();\n"
    "      _allLessons = lessons;\n"
    "      setState(() { _isLoading = false; _step = _reviewLessons.isEmpty ? ImportStep.confirm : ImportStep.review; });\n"
    "    } catch (e) { setState(() => _isLoading = false); _showError('خطأ في التحليل'); }\n"
    "  }\n"
    "\n"
    "  Future<void> _executeImport() async {\n"
    "    setState(() => _isLoading = true);\n"
    "    try {\n"
    "      final classesSnap = await FirebaseFirestore.instance.collection('Schools').doc(widget.schoolId).collection('Classes').get();\n"
    "      final classNameToId = <String, String>{};\n"
    "      for (final cls in classesSnap.docs) {\n"
    "        final data = cls.data(); final name = (data['name'] ?? '').toString().trim();\n"
    "        if (name.isNotEmpty) { classNameToId[name] = cls.id; classNameToId[name.replaceAll(' ', '')] = cls.id; }\n"
    "      }\n"
    "      final teachersSnap = await FirebaseFirestore.instance.collection('Schools').doc(widget.schoolId).collection('Teachers').get();\n"
    "      final teacherNameToId = <String, String>{};\n"
    "      for (final t in teachersSnap.docs) { final name = (t.data()['name'] ?? '').toString().trim(); if (name.isNotEmpty) teacherNameToId[name] = t.id; }\n"
    "      final teacherLessons = <String, List<Map<String, dynamic>>>{};\n"
    "      final classLessons = <String, List<Map<String, dynamic>>>{};\n"
    "      for (final lesson in _allLessons) {\n"
    "        final classId = classNameToId[lesson.className] ?? classNameToId[lesson.className.replaceAll(' ', '')];\n"
    "        final lessonMap = {'period': lesson.period, 'dayIndex': lesson.dayIndex, 'dayName': lesson.dayName, 'day': lesson.dayName,\n"
    "          'subject': lesson.resolvedSubject, 'rawSubject': lesson.rawSubject, 'className': lesson.className, 'teacherName': lesson.teacherName,\n"
    "          if (classId != null) 'classId': classId};\n"
    "        teacherLessons.putIfAbsent(lesson.teacherName, () => []).add(lessonMap);\n"
    "        if (classId != null) classLessons.putIfAbsent(classId, () => []).add(lessonMap);\n"
    "      }\n"
    "      await FirebaseFirestore.instance.collection('Schools').doc(widget.schoolId).collection('GeneralSchedule').add(\n"
    "          {'teacherSchedules': teacherLessons, 'source': 'excel_import_wizard', 'status': 'approved', 'createdAt': FieldValue.serverTimestamp()});\n"
    "      for (final entry in teacherLessons.entries) {\n"
    "        String? tid = teacherNameToId[entry.key];\n"
    "        if (tid == null) { for (final e in teacherNameToId.entries) { if (entry.key.contains(e.key) || e.key.contains(entry.key)) { tid = e.value; break; } } }\n"
    "        if (tid == null) continue;\n"
    "        await FirebaseFirestore.instance.collection('Schools').doc(widget.schoolId).collection('Teachers').doc(tid)\n"
    "            .update({'schedule': entry.value, 'scheduleUpdatedAt': FieldValue.serverTimestamp()});\n"
    "        await FirebaseFirestore.instance.collection('Schools').doc(widget.schoolId).collection('TeacherSchedules').doc(tid)\n"
    "            .set({'slots': entry.value, 'updatedAt': FieldValue.serverTimestamp(), 'source': 'excel_import_wizard'});\n"
    "      }\n"
    "      for (final entry in classLessons.entries) {\n"
    "        await FirebaseFirestore.instance.collection('Schools').doc(widget.schoolId).collection('Classes').doc(entry.key)\n"
    "            .collection('ClassSchedules').add({'lessons': entry.value, 'source': 'excel_import_wizard', 'status': 'approved', 'createdAt': FieldValue.serverTimestamp()});\n"
    "      }\n"
    "      setState(() => _isLoading = false);\n"
    "      widget.onImportComplete();\n"
    "      if (mounted) Navigator.of(context).pop(true);\n"
    "    } catch (e) { setState(() => _isLoading = false); _showError('فشل الاستيراد'); }\n"
    "  }\n"
    "\n"
    "  void _showError(String msg) {\n"
    "    if (!mounted) return;\n"
    "    ScaffoldMessenger.of(context).showSnackBar(SnackBar(\n"
    "      content: Text(msg), backgroundColor: _C.rose,\n"
    "      behavior: SnackBarBehavior.floating,\n"
    "      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))));\n"
    "  }\n"
)

p.write_text(c + dart, encoding='utf-8')
print('part2 ok')
