import pathlib
p = pathlib.Path('lib/src/features/schedule/presentation/excel_import_wizard.dart')
c = p.read_text(encoding='utf-8')

dart = (
    "\n"
    "  // ─── STEP 3: Review ──────────────────────────────────────────────────────\n"
    "  Widget _buildReviewStep() {\n"
    "    return Column(children: [\n"
    "      Container(\n"
    "        margin: const EdgeInsets.fromLTRB(24, 18, 24, 0),\n"
    "        padding: const EdgeInsets.all(14),\n"
    "        decoration: BoxDecoration(\n"
    "          color: _C.amber.withOpacity(0.08),\n"
    "          borderRadius: BorderRadius.circular(12),\n"
    "          border: Border.all(color: _C.amber.withOpacity(0.25)),\n"
    "        ),\n"
    "        child: Row(children: [\n"
    "          Container(width: 36, height: 36,\n"
    "            decoration: BoxDecoration(color: _C.amber.withOpacity(0.15), shape: BoxShape.circle),\n"
    "            child: const Icon(Icons.rate_review_rounded, color: _C.amber, size: 18)),\n"
    "          const SizedBox(width: 12),\n"
    "          Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "            Text(_reviewLessons.length.toString() + ' مادة تحتاج تحديد يدوي',\n"
    "                style: const TextStyle(color: _C.text, fontWeight: FontWeight.bold, fontSize: 14)),\n"
    "            const Text('كل تصحيح يُحفظ تلقائياً للمرات القادمة',\n"
    "                style: TextStyle(color: _C.textMuted, fontSize: 11)),\n"
    "          ])),\n"
    "        ]),\n"
    "      ),\n"
    "      const SizedBox(height: 12),\n"
    "      Expanded(child: ListView.builder(\n"
    "        padding: const EdgeInsets.symmetric(horizontal: 24),\n"
    "        itemCount: _reviewLessons.length,\n"
    "        itemBuilder: (context, i) => _buildReviewCard(_reviewLessons[i]),\n"
    "      )),\n"
    "      Padding(\n"
    "        padding: const EdgeInsets.all(20),\n"
    "        child: SizedBox(width: double.infinity, child: _primaryBtn(\n"
    "          'تأكيد المراجعة والمتابعة', Icons.check_rounded,\n"
    "          () => setState(() => _step = ImportStep.confirm), _C.emerald)),\n"
    "      ),\n"
    "    ]);\n"
    "  }\n"
    "\n"
    "  Widget _buildReviewCard(ImportedLesson lesson) {\n"
    "    final isResolved = lesson.matchResult.matched != null;\n"
    "    return Container(\n"
    "      margin: const EdgeInsets.only(bottom: 10),\n"
    "      decoration: BoxDecoration(\n"
    "        color: _C.card,\n"
    "        borderRadius: BorderRadius.circular(14),\n"
    "        border: Border.all(color: isResolved ? _C.emerald.withOpacity(0.3) : _C.amber.withOpacity(0.3)),\n"
    "      ),\n"
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "        Container(\n"
    "          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),\n"
    "          decoration: BoxDecoration(\n"
    "            color: isResolved ? _C.emerald.withOpacity(0.06) : _C.amber.withOpacity(0.06),\n"
    "            borderRadius: const BorderRadius.vertical(top: Radius.circular(14)),\n"
    "          ),\n"
    "          child: Row(children: [\n"
    "            Icon(isResolved ? Icons.check_circle_rounded : Icons.warning_amber_rounded,\n"
    "                color: isResolved ? _C.emerald : _C.amber, size: 16),\n"
    "            const SizedBox(width: 8),\n"
    "            Text('\"' + lesson.rawSubject + '\"',\n"
    "                style: const TextStyle(color: _C.text, fontWeight: FontWeight.bold, fontSize: 14)),\n"
    "            if (isResolved) ...[\n"
    "              const SizedBox(width: 8),\n"
    "              const Icon(Icons.arrow_forward_rounded, color: _C.textMuted, size: 12),\n"
    "              const SizedBox(width: 4),\n"
    "              Text(lesson.matchResult.matched!.officialName,\n"
    "                  style: const TextStyle(color: _C.emerald, fontSize: 12)),\n"
    "            ],\n"
    "          ]),\n"
    "        ),\n"
    "        Padding(\n"
    "          padding: const EdgeInsets.all(14),\n"
    "          child: DropdownButtonFormField<String>(\n"
    "            value: lesson.matchResult.matched?.id,\n"
    "            dropdownColor: _C.surface,\n"
    "            style: const TextStyle(color: _C.text, fontSize: 13),\n"
    "            decoration: InputDecoration(\n"
    "              labelText: 'اختر التصنيف الصحيح',\n"
    "              labelStyle: const TextStyle(color: _C.textMuted, fontSize: 12),\n"
    "              filled: true, fillColor: _C.surface,\n"
    "              contentPadding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),\n"
    "              border: OutlineInputBorder(borderRadius: BorderRadius.circular(10), borderSide: const BorderSide(color: _C.border)),\n"
    "              enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(10), borderSide: const BorderSide(color: _C.border)),\n"
    "              focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(10), borderSide: const BorderSide(color: _C.violet, width: 1.5)),\n"
    "            ),\n"
    "            items: [\n"
    "              const DropdownMenuItem<String>(value: null, child: Text('-- غير محدد --', style: TextStyle(color: _C.textMuted))),\n"
    "              ...SubjectMatcher.defaultSubjects.map((s) => DropdownMenuItem(\n"
    "                value: s.id, child: Text(s.officialName, style: const TextStyle(color: _C.text)))),\n"
    "            ],\n"
    "            onChanged: (id) {\n"
    "              if (id == null) return;\n"
    "              final master = SubjectMatcher.findById(id);\n"
    "              if (master == null) return;\n"
    "              setState(() {\n"
    "                lesson.matchResult = SubjectMatchResult(rawName: lesson.rawSubject, matched: master, confidence: MatchConfidence.high);\n"
    "                for (final l in _allLessons) { if (l.rawSubject == lesson.rawSubject) l.matchResult = lesson.matchResult; }\n"
    "              });\n"
    "              SubjectMatcher.saveAlias(widget.schoolId, lesson.rawSubject, id);\n"
    "            },\n"
    "          ),\n"
    "        ),\n"
    "        if (isResolved)\n"
    "          Padding(\n"
    "            padding: const EdgeInsets.fromLTRB(14, 0, 14, 12),\n"
    "            child: Row(children: [\n"
    "              const Icon(Icons.bookmark_added_rounded, color: _C.emerald, size: 13),\n"
    "              const SizedBox(width: 6),\n"
    "              Expanded(child: Text(\n"
    "                'سيُحفظ كمرادف دائم: \"' + lesson.rawSubject + '\" → ' + (lesson.matchResult.matched?.officialName ?? ''),\n"
    "                style: const TextStyle(color: _C.emerald, fontSize: 11))),\n"
    "            ]),\n"
    "          ),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  // ─── STEP 4: Confirm ─────────────────────────────────────────────────────\n"
    "  Widget _buildConfirmStep() {\n"
    "    final teacherCount = _allLessons.map((l) => l.teacherName).toSet().length;\n"
    "    final subjectCount = _allLessons.map((l) => l.resolvedSubject).toSet().length;\n"
    "    final classCount = _allLessons.map((l) => l.className).where((c) => c.isNotEmpty).toSet().length;\n"
    "    return SingleChildScrollView(\n"
    "      padding: const EdgeInsets.all(28),\n"
    "      child: Column(children: [\n"
    "        // Success icon with glow\n"
    "        AnimatedBuilder(\n"
    "          animation: _pulseAnim,\n"
    "          builder: (_, __) => Container(\n"
    "            width: 90, height: 90,\n"
    "            decoration: BoxDecoration(\n"
    "              shape: BoxShape.circle,\n"
    "              gradient: RadialGradient(colors: [_C.emerald.withOpacity(0.2), Colors.transparent]),\n"
    "              boxShadow: [BoxShadow(color: _C.emerald.withOpacity(_pulseAnim.value * 0.3), blurRadius: 30)],\n"
    "              border: Border.all(color: _C.emerald.withOpacity(0.4), width: 1.5),\n"
    "            ),\n"
    "            child: const Icon(Icons.rocket_launch_rounded, color: _C.emerald, size: 40),\n"
    "          ),\n"
    "        ),\n"
    "        const SizedBox(height: 16),\n"
    "        const Text('جاهز للاستيراد', style: TextStyle(color: _C.text, fontSize: 22, fontWeight: FontWeight.bold)),\n"
    "        const SizedBox(height: 4),\n"
    "        Text('سيتم حفظ الجدول وتوزيعه على المعلمين والفصول', style: TextStyle(color: _C.textMuted, fontSize: 12)),\n"
    "        const SizedBox(height: 24),\n"
    "        // Stats grid\n"
    "        Row(children: [\n"
    "          _confirmTile(Icons.people_rounded, teacherCount.toString(), 'معلم', _C.violet),\n"
    "          const SizedBox(width: 10),\n"
    "          _confirmTile(Icons.menu_book_rounded, subjectCount.toString(), 'مادة', _C.sky),\n"
    "          const SizedBox(width: 10),\n"
    "          _confirmTile(Icons.class_rounded, classCount.toString(), 'فصل', _C.amber),\n"
    "          const SizedBox(width: 10),\n"
    "          _confirmTile(Icons.event_note_rounded, _allLessons.length.toString(), 'حصة', _C.emerald),\n"
    "        ]),\n"
    "        const SizedBox(height: 28),\n"
    "        SizedBox(width: double.infinity, child: _primaryBtn(\n"
    "          'إكمال الاستيراد', Icons.cloud_upload_rounded, _executeImport, _C.emerald)),\n"
    "        const SizedBox(height: 10),\n"
    "        TextButton(\n"
    "          onPressed: () => setState(() => _step = _reviewLessons.isEmpty ? ImportStep.analyze : ImportStep.review),\n"
    "          child: const Text('رجوع للمراجعة', style: TextStyle(color: _C.textMuted, fontSize: 12)),\n"
    "        ),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  Widget _confirmTile(IconData icon, String value, String label, Color color) {\n"
    "    return Expanded(child: Container(\n"
    "      padding: const EdgeInsets.symmetric(vertical: 16),\n"
    "      decoration: BoxDecoration(\n"
    "        color: _C.card,\n"
    "        borderRadius: BorderRadius.circular(14),\n"
    "        border: Border.all(color: color.withOpacity(0.2)),\n"
    "        boxShadow: [BoxShadow(color: color.withOpacity(0.06), blurRadius: 16)],\n"
    "      ),\n"
    "      child: Column(children: [\n"
    "        Container(width: 36, height: 36,\n"
    "          decoration: BoxDecoration(color: color.withOpacity(0.12), shape: BoxShape.circle),\n"
    "          child: Icon(icon, color: color, size: 18)),\n"
    "        const SizedBox(height: 8),\n"
    "        Text(value, style: TextStyle(color: color, fontSize: 24, fontWeight: FontWeight.bold,\n"
    "            shadows: [Shadow(color: color.withOpacity(0.4), blurRadius: 8)])),\n"
    "        Text(label, style: const TextStyle(color: _C.textMuted, fontSize: 10)),\n"
    "      ]),\n"
    "    ));\n"
    "  }\n"
    "\n"
    "  // ─── Shared Button ────────────────────────────────────────────────────────\n"
    "  Widget _primaryBtn(String label, IconData icon, VoidCallback onTap, Color color) {\n"
    "    return ElevatedButton.icon(\n"
    "      onPressed: onTap,\n"
    "      icon: Icon(icon, size: 18),\n"
    "      label: Text(label, style: const TextStyle(fontSize: 14, fontWeight: FontWeight.bold)),\n"
    "      style: ElevatedButton.styleFrom(\n"
    "        backgroundColor: color,\n"
    "        foregroundColor: Colors.white,\n"
    "        padding: const EdgeInsets.symmetric(vertical: 16),\n"
    "        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),\n"
    "        elevation: 0,\n"
    "        shadowColor: color.withOpacity(0.4),\n"
    "      ).copyWith(elevation: WidgetStateProperty.resolveWith((s) => s.contains(WidgetState.hovered) ? 8 : 0)),\n"
    "    );\n"
    "  }\n"
    "}\n"
    "\n"
    "Future<bool?> showExcelImportWizard(\n"
    "    BuildContext context, String schoolId, VoidCallback onComplete) {\n"
    "  return showDialog<bool>(\n"
    "    context: context,\n"
    "    barrierDismissible: false,\n"
    "    barrierColor: Colors.black.withOpacity(0.7),\n"
    "    builder: (_) => ExcelImportWizard(schoolId: schoolId, onImportComplete: onComplete),\n"
    "  );\n"
    "}\n"
)

p.write_text(c + dart, encoding='utf-8')
print('part5 ok')
