import pathlib
p = pathlib.Path('lib/src/features/schedule/presentation/excel_import_wizard.dart')
c = p.read_text(encoding='utf-8')

dart = (
    "\n"
    "  // ─── BUILD ───────────────────────────────────────────────────────────────\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    return Dialog(\n"
    "      backgroundColor: Colors.transparent,\n"
    "      insetPadding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),\n"
    "      child: Container(\n"
    "        width: 760,\n"
    "        constraints: const BoxConstraints(maxHeight: 740),\n"
    "        decoration: BoxDecoration(\n"
    "          color: _C.bg,\n"
    "          borderRadius: BorderRadius.circular(24),\n"
    "          border: Border.all(color: _C.violet.withOpacity(0.25), width: 1),\n"
    "          boxShadow: [\n"
    "            BoxShadow(color: _C.violet.withOpacity(0.15), blurRadius: 60, spreadRadius: -10),\n"
    "            BoxShadow(color: Colors.black.withOpacity(0.6), blurRadius: 30),\n"
    "          ],\n"
    "        ),\n"
    "        child: ClipRRect(\n"
    "          borderRadius: BorderRadius.circular(24),\n"
    "          child: Column(\n"
    "            mainAxisSize: MainAxisSize.min,\n"
    "            children: [\n"
    "              _buildHeader(),\n"
    "              _buildStepRail(),\n"
    "              Flexible(child: _buildStepContent()),\n"
    "            ],\n"
    "          ),\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  // ─── Header ──────────────────────────────────────────────────────────────\n"
    "  Widget _buildHeader() {\n"
    "    return Container(\n"
    "      padding: const EdgeInsets.fromLTRB(24, 20, 16, 16),\n"
    "      decoration: BoxDecoration(\n"
    "        gradient: LinearGradient(\n"
    "          colors: [_C.violet.withOpacity(0.18), _C.surface],\n"
    "          begin: Alignment.centerRight, end: Alignment.centerLeft),\n"
    "        border: Border(bottom: BorderSide(color: _C.border)),\n"
    "      ),\n"
    "      child: Row(children: [\n"
    "        Container(\n"
    "          width: 42, height: 42,\n"
    "          decoration: BoxDecoration(\n"
    "            gradient: LinearGradient(colors: [_C.violet, _C.sky], begin: Alignment.topLeft, end: Alignment.bottomRight),\n"
    "            borderRadius: BorderRadius.circular(12),\n"
    "            boxShadow: [BoxShadow(color: _C.violet.withOpacity(0.4), blurRadius: 12, offset: const Offset(0, 4))],\n"
    "          ),\n"
    "          child: const Icon(Icons.table_chart_rounded, color: Colors.white, size: 22),\n"
    "        ),\n"
    "        const SizedBox(width: 14),\n"
    "        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "          const Text('استيراد جدول Excel', style: TextStyle(color: _C.text, fontSize: 17, fontWeight: FontWeight.bold)),\n"
    "          Text('مطابقة ذكية للمواد مع حفظ تلقائي للمرادفات',\n"
    "              style: TextStyle(color: _C.textMuted, fontSize: 11)),\n"
    "        ])),\n"
    "        IconButton(\n"
    "          icon: Icon(Icons.close_rounded, color: _C.textMuted),\n"
    "          onPressed: () => Navigator.of(context).pop(),\n"
    "          style: IconButton.styleFrom(backgroundColor: _C.card),\n"
    "        ),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  // ─── Step Rail ───────────────────────────────────────────────────────────\n"
    "  Widget _buildStepRail() {\n"
    "    final steps = [\n"
    "      (Icons.upload_file_rounded, 'رفع الملف'),\n"
    "      (Icons.analytics_rounded, 'تحليل'),\n"
    "      (Icons.rate_review_rounded, 'مراجعة'),\n"
    "      (Icons.rocket_launch_rounded, 'استيراد'),\n"
    "    ];\n"
    "    final idx = _step.index;\n"
    "    return Container(\n"
    "      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),\n"
    "      color: _C.surface,\n"
    "      child: Row(children: List.generate(steps.length, (i) {\n"
    "        final done = i < idx;\n"
    "        final active = i == idx;\n"
    "        final color = done ? _C.emerald : active ? _C.violet : _C.border;\n"
    "        return Expanded(child: Row(children: [\n"
    "          Expanded(child: Column(children: [\n"
    "            AnimatedContainer(\n"
    "              duration: const Duration(milliseconds: 300),\n"
    "              width: active ? 36 : 30, height: active ? 36 : 30,\n"
    "              decoration: BoxDecoration(\n"
    "                shape: BoxShape.circle,\n"
    "                color: done ? _C.emerald.withOpacity(0.15) : active ? _C.violet.withOpacity(0.15) : Colors.transparent,\n"
    "                border: Border.all(color: color, width: active ? 2 : 1),\n"
    "                boxShadow: active ? [BoxShadow(color: _C.violet.withOpacity(0.4), blurRadius: 12)] : [],\n"
    "              ),\n"
    "              child: Center(child: done\n"
    "                  ? Icon(Icons.check_rounded, color: _C.emerald, size: 14)\n"
    "                  : Icon(steps[i].$1, color: active ? _C.violetLt : _C.textMuted, size: active ? 16 : 13)),\n"
    "            ),\n"
    "            const SizedBox(height: 5),\n"
    "            Text(steps[i].$2, style: TextStyle(\n"
    "                color: active ? _C.violetLt : done ? _C.emerald : _C.textMuted,\n"
    "                fontSize: 10, fontWeight: active ? FontWeight.bold : FontWeight.normal),\n"
    "                textAlign: TextAlign.center),\n"
    "          ])),\n"
    "          if (i < steps.length - 1)\n"
    "            Expanded(child: Container(\n"
    "              height: 1, margin: const EdgeInsets.only(bottom: 20),\n"
    "              decoration: BoxDecoration(\n"
    "                gradient: LinearGradient(colors: [\n"
    "                  done ? _C.emerald : _C.border,\n"
    "                  i + 1 <= idx ? _C.emerald : _C.border,\n"
    "                ])),\n"
    "            )),\n"
    "        ]));\n"
    "      })),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  Widget _buildStepContent() {\n"
    "    if (_isLoading) return _buildLoadingState();\n"
    "    switch (_step) {\n"
    "      case ImportStep.upload:  return _buildUploadStep();\n"
    "      case ImportStep.analyze: return _buildAnalyzeStep();\n"
    "      case ImportStep.review:  return _buildReviewStep();\n"
    "      case ImportStep.confirm: return _buildConfirmStep();\n"
    "    }\n"
    "  }\n"
    "\n"
    "  Widget _buildLoadingState() {\n"
    "    return Center(child: Padding(\n"
    "      padding: const EdgeInsets.all(60),\n"
    "      child: Column(mainAxisSize: MainAxisSize.min, children: [\n"
    "        AnimatedBuilder(\n"
    "          animation: _pulseAnim,\n"
    "          builder: (_, __) => Container(\n"
    "            width: 72, height: 72,\n"
    "            decoration: BoxDecoration(\n"
    "              shape: BoxShape.circle,\n"
    "              border: Border.all(color: _C.violet.withOpacity(_pulseAnim.value), width: 2),\n"
    "              boxShadow: [BoxShadow(color: _C.violet.withOpacity(_pulseAnim.value * 0.4), blurRadius: 24)],\n"
    "            ),\n"
    "            child: const Center(child: CircularProgressIndicator(\n"
    "              color: _C.violetLt, strokeWidth: 2)),\n"
    "          ),\n"
    "        ),\n"
    "        const SizedBox(height: 20),\n"
    "        const Text('جاري التحليل الذكي...', style: TextStyle(color: _C.text, fontSize: 15, fontWeight: FontWeight.w500)),\n"
    "        const SizedBox(height: 6),\n"
    "        Text('يتم مطابقة المواد مع قاعدة البيانات', style: TextStyle(color: _C.textMuted, fontSize: 12)),\n"
    "      ]),\n"
    "    ));\n"
    "  }\n"
)

p.write_text(c + dart, encoding='utf-8')
print('part3 ok')
