import pathlib

out = pathlib.Path('lib/src/features/schedule/presentation/excel_import_wizard.dart')
content = out.read_text(encoding='utf-8')

review_step = (
    "\n"
    "  Widget _buildReviewStep() {\n"
    "    return Column(children: [\n"
    "      Padding(\n"
    "        padding: const EdgeInsets.fromLTRB(22, 18, 22, 0),\n"
    "        child: Row(children: [\n"
    "          const Icon(Icons.rate_review, color: Colors.orange),\n"
    "          const SizedBox(width: 8),\n"
    "          Text(\n"
    "            _reviewLessons.length.toString() + ' مادة تحتاج تحديد',\n"
    "            style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),\n"
    "        ]),\n"
    "      ),\n"
    "      const Padding(\n"
    "        padding: EdgeInsets.fromLTRB(22, 5, 22, 10),\n"
    "        child: Text('حدد التصنيف الصحيح. سيحفظ تلقائيا للمرات القادمة.',\n"
    "            style: TextStyle(color: Colors.white54, fontSize: 12)),\n"
    "      ),\n"
    "      Expanded(child: ListView.builder(\n"
    "        padding: const EdgeInsets.symmetric(horizontal: 22),\n"
    "        itemCount: _reviewLessons.length,\n"
    "        itemBuilder: (context, i) => _buildReviewCard(_reviewLessons[i]),\n"
    "      )),\n"
    "      Padding(\n"
    "        padding: const EdgeInsets.all(18),\n"
    "        child: SizedBox(width: double.infinity, child: ElevatedButton.icon(\n"
    "          onPressed: () => setState(() => _step = ImportStep.confirm),\n"
    "          icon: const Icon(Icons.check),\n"
    "          label: const Text('تاكيد المراجعة والمتابعة'),\n"
    "          style: ElevatedButton.styleFrom(\n"
    "            backgroundColor: Colors.green,\n"
    "            foregroundColor: Colors.white,\n"
    "            padding: const EdgeInsets.symmetric(vertical: 14),\n"
    "            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),\n"
    "          ),\n"
    "        )),\n"
    "      ),\n"
    "    ]);\n"
    "  }\n"
    "\n"
    "  Widget _buildReviewCard(ImportedLesson lesson) {\n"
    "    return Container(\n"
    "      margin: const EdgeInsets.only(bottom: 12),\n"
    "      padding: const EdgeInsets.all(14),\n"
    "      decoration: BoxDecoration(\n"
    "        color: Colors.orange.withOpacity(0.07),\n"
    "        borderRadius: BorderRadius.circular(12),\n"
    "        border: Border.all(color: Colors.orange.withOpacity(0.3)),\n"
    "      ),\n"
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [\n"
    "        Row(children: [\n"
    "          const Icon(Icons.warning_amber, color: Colors.orange, size: 16),\n"
    "          const SizedBox(width: 6),\n"
    "          Expanded(child: Text('\"' + lesson.rawSubject + '\"',\n"
    "              style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 14))),\n"
    "        ]),\n"
    "        const SizedBox(height: 10),\n"
    "        DropdownButtonFormField<String>(\n"
    "          value: lesson.matchResult.matched?.id,\n"
    "          dropdownColor: const Color(0xFF1A2E42),\n"
    "          style: const TextStyle(color: Colors.white),\n"
    "          decoration: InputDecoration(\n"
    "            labelText: 'اختر التصنيف',\n"
    "            labelStyle: const TextStyle(color: Colors.white54),\n"
    "            filled: true,\n"
    "            fillColor: Colors.white.withOpacity(0.05),\n"
    "            border: OutlineInputBorder(borderRadius: BorderRadius.circular(8),\n"
    "                borderSide: const BorderSide(color: Colors.white24)),\n"
    "            enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(8),\n"
    "                borderSide: const BorderSide(color: Colors.white24)),\n"
    "          ),\n"
    "          items: [\n"
    "            const DropdownMenuItem<String>(value: null,\n"
    "                child: Text('-- غير محدد --', style: TextStyle(color: Colors.white54))),\n"
    "            ...SubjectMatcher.defaultSubjects.map((s) => DropdownMenuItem(\n"
    "              value: s.id,\n"
    "              child: Text(s.officialName, style: const TextStyle(color: Colors.white)),\n"
    "            )),\n"
    "          ],\n"
    "          onChanged: (id) {\n"
    "            if (id == null) return;\n"
    "            final master = SubjectMatcher.findById(id);\n"
    "            if (master == null) return;\n"
    "            setState(() {\n"
    "              lesson.matchResult = SubjectMatchResult(\n"
    "                rawName: lesson.rawSubject,\n"
    "                matched: master,\n"
    "                confidence: MatchConfidence.high,\n"
    "              );\n"
    "              for (final l in _allLessons) {\n"
    "                if (l.rawSubject == lesson.rawSubject) l.matchResult = lesson.matchResult;\n"
    "              }\n"
    "            });\n"
    "            SubjectMatcher.saveAlias(widget.schoolId, lesson.rawSubject, id);\n"
    "          },\n"
    "        ),\n"
    "        if (lesson.matchResult.matched != null) ...[\n"
    "          const SizedBox(height: 8),\n"
    "          Row(children: [\n"
    "            const Icon(Icons.check_circle, color: Colors.green, size: 13),\n"
    "            const SizedBox(width: 5),\n"
    "            Expanded(child: Text(\n"
    "              'سيحفظ كمرادف: \"' + lesson.rawSubject + '\" -> ' + (lesson.matchResult.matched?.officialName ?? ''),\n"
    "              style: const TextStyle(color: Colors.green, fontSize: 11))),\n"
    "          ]),\n"
    "        ],\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
)

out.write_text(content + review_step, encoding='utf-8')
print('review step ok')
