import pathlib

out = pathlib.Path('lib/src/features/schedule/presentation/excel_import_wizard.dart')
content = out.read_text(encoding='utf-8')

confirm_step = (
    "\n"
    "  Widget _buildConfirmStep() {\n"
    "    final teacherCount = _allLessons.map((l) => l.teacherName).toSet().length;\n"
    "    final subjectCount = _allLessons.map((l) => l.resolvedSubject).toSet().length;\n"
    "    final classCount = _allLessons.map((l) => l.className).where((c) => c.isNotEmpty).toSet().length;\n"
    "    return Padding(\n"
    "      padding: const EdgeInsets.all(28),\n"
    "      child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [\n"
    "        Container(\n"
    "          width: 80, height: 80,\n"
    "          decoration: BoxDecoration(\n"
    "            color: Colors.green.withOpacity(0.1),\n"
    "            shape: BoxShape.circle,\n"
    "            border: Border.all(color: Colors.green.withOpacity(0.4), width: 2),\n"
    "          ),\n"
    "          child: const Icon(Icons.check_circle_outline, size: 44, color: Colors.green),\n"
    "        ),\n"
    "        const SizedBox(height: 18),\n"
    "        const Text('جاهز للاستيراد',\n"
    "            style: TextStyle(color: Colors.white, fontSize: 22, fontWeight: FontWeight.bold)),\n"
    "        const SizedBox(height: 22),\n"
    "        Row(children: [\n"
    "          _confirmStat(Icons.people, teacherCount.toString(), 'معلم', Colors.blue),\n"
    "          const SizedBox(width: 10),\n"
    "          _confirmStat(Icons.book, subjectCount.toString(), 'مادة', Colors.purple),\n"
    "          const SizedBox(width: 10),\n"
    "          _confirmStat(Icons.class_, classCount.toString(), 'فصل', Colors.teal),\n"
    "          const SizedBox(width: 10),\n"
    "          _confirmStat(Icons.event_note, _allLessons.length.toString(), 'حصة', Colors.orange),\n"
    "        ]),\n"
    "        const SizedBox(height: 26),\n"
    "        SizedBox(width: double.infinity, child: ElevatedButton.icon(\n"
    "          onPressed: _executeImport,\n"
    "          icon: const Icon(Icons.cloud_upload),\n"
    "          label: const Text('اكمال الاستيراد', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),\n"
    "          style: ElevatedButton.styleFrom(\n"
    "            backgroundColor: Colors.green,\n"
    "            foregroundColor: Colors.white,\n"
    "            padding: const EdgeInsets.symmetric(vertical: 18),\n"
    "            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),\n"
    "            elevation: 4,\n"
    "          ),\n"
    "        )),\n"
    "        const SizedBox(height: 10),\n"
    "        TextButton(\n"
    "          onPressed: () => setState(() =>\n"
    "              _step = _reviewLessons.isEmpty ? ImportStep.analyze : ImportStep.review),\n"
    "          child: const Text('رجوع', style: TextStyle(color: Colors.white38)),\n"
    "        ),\n"
    "      ]),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  Widget _confirmStat(IconData icon, String value, String label, Color color) {\n"
    "    return Expanded(child: Container(\n"
    "      padding: const EdgeInsets.all(12),\n"
    "      decoration: BoxDecoration(\n"
    "        color: color.withOpacity(0.1),\n"
    "        borderRadius: BorderRadius.circular(10),\n"
    "        border: Border.all(color: color.withOpacity(0.3)),\n"
    "      ),\n"
    "      child: Column(children: [\n"
    "        Icon(icon, color: color, size: 20),\n"
    "        const SizedBox(height: 5),\n"
    "        Text(value, style: TextStyle(color: color, fontSize: 20, fontWeight: FontWeight.bold)),\n"
    "        Text(label, style: const TextStyle(color: Colors.white54, fontSize: 10)),\n"
    "      ]),\n"
    "    ));\n"
    "  }\n"
    "}\n"
    "\n"
    "Future<bool?> showExcelImportWizard(\n"
    "    BuildContext context, String schoolId, VoidCallback onComplete) {\n"
    "  return showDialog<bool>(\n"
    "    context: context,\n"
    "    barrierDismissible: false,\n"
    "    builder: (_) => ExcelImportWizard(schoolId: schoolId, onImportComplete: onComplete),\n"
    "  );\n"
    "}\n"
)

out.write_text(content + confirm_step, encoding='utf-8')
print('confirm step ok')
