import pathlib

# Colors palette:
# Background: #0A0A0F (near black with purple tint)
# Card: rgba(255,255,255,0.04) glassmorphism
# Accent 1: #7C3AED (electric violet)
# Accent 2: #F59E0B (amber/gold)
# Accent 3: #10B981 (emerald)
# Neon blue: #38BDF8
# Border: rgba(124,58,237,0.3)

dart = (
    "/// excel_import_wizard.dart\n"
    "/// Wizard استيراد جدول Excel — تصميم Obsidian Premium\n"
    "library;\n"
    "\n"
    "import 'package:flutter/material.dart';\n"
    "import 'package:cloud_firestore/cloud_firestore.dart';\n"
    "import 'package:file_picker/file_picker.dart';\n"
    "import 'package:excel/excel.dart' as excel;\n"
    "import 'package:flutter/foundation.dart' show kIsWeb;\n"
    "import 'package:cross_file/cross_file.dart';\n"
    "import '../services/subject_matcher.dart';\n"
    "\n"
    "// ─── Palette ─────────────────────────────────────────────────────────────────\n"
    "class _C {\n"
    "  static const bg        = Color(0xFF0A0A0F);\n"
    "  static const surface   = Color(0xFF13131A);\n"
    "  static const card      = Color(0xFF1C1C28);\n"
    "  static const violet    = Color(0xFF7C3AED);\n"
    "  static const violetLt  = Color(0xFFA78BFA);\n"
    "  static const amber     = Color(0xFFF59E0B);\n"
    "  static const emerald   = Color(0xFF10B981);\n"
    "  static const sky       = Color(0xFF38BDF8);\n"
    "  static const rose      = Color(0xFFF43F5E);\n"
    "  static const border    = Color(0xFF2D2D3F);\n"
    "  static const text      = Color(0xFFF1F5F9);\n"
    "  static const textMuted = Color(0xFF64748B);\n"
    "}\n"
    "\n"
    "enum ImportStep { upload, analyze, review, confirm }\n"
    "\n"
    "class ImportedLesson {\n"
    "  final String teacherName;\n"
    "  final String rawSubject;\n"
    "  SubjectMatchResult matchResult;\n"
    "  final String className;\n"
    "  final String dayName;\n"
    "  final int dayIndex;\n"
    "  final int period;\n"
    "\n"
    "  ImportedLesson({\n"
    "    required this.teacherName,\n"
    "    required this.rawSubject,\n"
    "    required this.matchResult,\n"
    "    required this.className,\n"
    "    required this.dayName,\n"
    "    required this.dayIndex,\n"
    "    required this.period,\n"
    "  });\n"
    "\n"
    "  String get resolvedSubject => matchResult.matched?.officialName ?? rawSubject;\n"
    "}\n"
    "\n"
    "class ExcelImportWizard extends StatefulWidget {\n"
    "  final String schoolId;\n"
    "  final VoidCallback onImportComplete;\n"
    "  const ExcelImportWizard({super.key, required this.schoolId, required this.onImportComplete});\n"
    "  @override\n"
    "  State<ExcelImportWizard> createState() => _ExcelImportWizardState();\n"
    "}\n"
    "\n"
    "class _ExcelImportWizardState extends State<ExcelImportWizard>\n"
    "    with SingleTickerProviderStateMixin {\n"
    "  ImportStep _step = ImportStep.upload;\n"
    "  bool _isLoading = false;\n"
    "  String _fileName = '';\n"
    "  excel.Excel? _workbook;\n"
    "  List<ImportedLesson> _allLessons = [];\n"
    "  List<ImportedLesson> _reviewLessons = [];\n"
    "  Map<String, int> _subjectStats = {};\n"
    "  int _knownCount = 0;\n"
    "  int _unknownCount = 0;\n"
    "  late AnimationController _pulseCtrl;\n"
    "  late Animation<double> _pulseAnim;\n"
    "  final List<String> _days = ['الاحد', 'الاثنين', 'الثلاثاء', 'الاربعاء', 'الخميس'];\n"
    "\n"
    "  @override\n"
    "  void initState() {\n"
    "    super.initState();\n"
    "    SubjectMatcher.loadFromFirestore(widget.schoolId);\n"
    "    _pulseCtrl = AnimationController(vsync: this, duration: const Duration(seconds: 2))\n"
    "      ..repeat(reverse: true);\n"
    "    _pulseAnim = Tween<double>(begin: 0.6, end: 1.0).animate(\n"
    "        CurvedAnimation(parent: _pulseCtrl, curve: Curves.easeInOut));\n"
    "  }\n"
    "\n"
    "  @override\n"
    "  void dispose() {\n"
    "    _pulseCtrl.dispose();\n"
    "    super.dispose();\n"
    "  }\n"
)

pathlib.Path('lib/src/features/schedule/presentation/excel_import_wizard.dart').write_text(dart, encoding='utf-8')
print('part1 ok')
