import pathlib

p = pathlib.Path("lib/src/features/wait_management/presentation/wait_management_screen.dart")
c = p.read_text(encoding="utf-8")

lines = []
lines.append("  @override")
lines.append("  Widget build(BuildContext context) {")
lines.append("    return Scaffold(")
lines.append("      backgroundColor: const Color(0xFFF8FAFF),")
lines.append("      body: Column(children: [")
lines.append("        _buildTopBar(),")
lines.append("        if (_isLoading)")
lines.append("          const Expanded(child: Center(child: CircularProgressIndicator(color: Color(0xFF4F46E5))))")
lines.append("        else")
lines.append("          Expanded(child: _buildBody()),")
lines.append("      ]),")
lines.append("    );")
lines.append("  }")
lines.append("")
lines.append("  Widget _buildTopBar() {")
lines.append("    return Container(")
lines.append("      padding: const EdgeInsets.fromLTRB(16, 48, 16, 12),")
lines.append("      decoration: BoxDecoration(")
lines.append("        color: Colors.white,")
lines.append("        border: const Border(bottom: BorderSide(color: Color(0xFFE2E8F0))),")
lines.append("        boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 8, offset: const Offset(0, 2))],")
lines.append("      ),")
lines.append("      child: Column(children: [")
lines.append("        Row(children: [")
lines.append("          GestureDetector(")
lines.append("            onTap: () => Navigator.of(context).pop(),")
lines.append("            child: Container(width: 36, height: 36,")
lines.append("              decoration: BoxDecoration(color: const Color(0xFFF8FAFF), borderRadius: BorderRadius.circular(10),")
lines.append("                  border: Border.all(color: const Color(0xFFE2E8F0))),")
lines.append("              child: const Icon(Icons.arrow_back_ios_new_rounded, color: Color(0xFF64748B), size: 15)),")
lines.append("          ),")
lines.append("          const SizedBox(width: 12),")
lines.append("          Container(width: 40, height: 40,")
lines.append("            decoration: BoxDecoration(")
lines.append("              gradient: const LinearGradient(colors: [Color(0xFF4F46E5), Color(0xFF06B6D4)],")
lines.append("                  begin: Alignment.topLeft, end: Alignment.bottomRight),")
lines.append("              borderRadius: BorderRadius.circular(12),")
lines.append("              boxShadow: [BoxShadow(color: const Color(0xFF4F46E5).withOpacity(0.3), blurRadius: 10, offset: const Offset(0, 4))]),")
lines.append("            child: const Icon(Icons.hourglass_top_rounded, color: Colors.white, size: 20)),")
lines.append("          const SizedBox(width: 10),")
lines.append("          const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
lines.append("            Text('جدول الانتظار', style: TextStyle(color: Color(0xFF1E293B), fontSize: 16, fontWeight: FontWeight.bold)),")
lines.append("            Text('توزيع ذكي حسب النصاب', style: TextStyle(color: Color(0xFF64748B), fontSize: 11)),")
lines.append("          ])),")
lines.append("          // Wait count selector")
lines.append("          Container(")
lines.append("            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),")
lines.append("            decoration: BoxDecoration(")
lines.append("              color: const Color(0xFFF8FAFF), borderRadius: BorderRadius.circular(10),")
lines.append("              border: Border.all(color: const Color(0xFFE2E8F0))),")
lines.append("            child: Row(mainAxisSize: MainAxisSize.min, children: [")
lines.append("              const Text('منتظرين:', style: TextStyle(color: Color(0xFF64748B), fontSize: 11)),")
lines.append("              const SizedBox(width: 6),")
lines.append("              ...List.generate(4, (i) => GestureDetector(")
lines.append("                onTap: () => setState(() { _waitCount = i + 1; _generateSchedule(); }),")
lines.append("                child: Container(")
lines.append("                  width: 28, height: 28, margin: const EdgeInsets.only(left: 4),")
lines.append("                  decoration: BoxDecoration(")
lines.append("                    color: _waitCount == i + 1 ? _wColors[i] : _wColors[i].withOpacity(0.1),")
lines.append("                    borderRadius: BorderRadius.circular(8),")
lines.append("                    border: Border.all(color: _wColors[i].withOpacity(0.4))),")
lines.append("                  child: Center(child: Text('${i + 1}', style: TextStyle(")
lines.append("                    color: _waitCount == i + 1 ? Colors.white : _wColors[i],")
lines.append("                    fontSize: 12, fontWeight: FontWeight.bold))),")
lines.append("                ),")
lines.append("              )),")
lines.append("            ]),")
lines.append("          ),")
lines.append("        ]),")
lines.append("        const SizedBox(height: 10),")
lines.append("        // Action buttons")
lines.append("        Row(children: [")
lines.append("          _actionBtn('استيراد من الجدول', Icons.download_rounded, const Color(0xFF4F46E5), _importFromGeneralSchedule),")
lines.append("          const SizedBox(width: 8),")
lines.append("          _actionBtn('توزيع تلقائي', Icons.auto_fix_high_rounded, const Color(0xFF059669), () => setState(() => _generateSchedule())),")
lines.append("          const Spacer(),")
lines.append("          ElevatedButton.icon(")
lines.append("            onPressed: _isSaving ? null : _saveSchedule,")
lines.append("            icon: _isSaving ? const SizedBox(width: 14, height: 14, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))")
lines.append("                : const Icon(Icons.save_rounded, size: 15),")
lines.append("            label: const Text('حفظ', style: TextStyle(fontSize: 13, fontWeight: FontWeight.bold)),")
lines.append("            style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF059669), foregroundColor: Colors.white,")
lines.append("              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),")
lines.append("              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)), elevation: 0),")
lines.append("          ),")
lines.append("        ]),")
lines.append("      ]),")
lines.append("    );")
lines.append("  }")
lines.append("")
lines.append("  Widget _actionBtn(String label, IconData icon, Color color, VoidCallback onTap) {")
lines.append("    return OutlinedButton.icon(")
lines.append("      onPressed: onTap,")
lines.append("      icon: Icon(icon, size: 14, color: color),")
lines.append("      label: Text(label, style: TextStyle(fontSize: 12, color: color)),")
lines.append("      style: OutlinedButton.styleFrom(")
lines.append("        side: BorderSide(color: color.withOpacity(0.4)),")
lines.append("        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),")
lines.append("        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10))),")
lines.append("    );")
lines.append("  }")
lines.append("")

p.write_text(c + "\n".join(lines), encoding="utf-8")
print("build+topbar ok")
