import pathlib

p = pathlib.Path("lib/src/features/wait_management/presentation/wait_management_screen.dart")
c = p.read_text(encoding="utf-8")

lines = []
lines.append("class WaitManagementScreen extends ConsumerStatefulWidget {")
lines.append("  const WaitManagementScreen({super.key});")
lines.append("  @override")
lines.append("  ConsumerState<WaitManagementScreen> createState() => _WaitManagementScreenState();")
lines.append("}")
lines.append("")
lines.append("class _WaitManagementScreenState extends ConsumerState<WaitManagementScreen> {")
lines.append("  String? _schoolId;")
lines.append("  List<Map<String, dynamic>> _teachers = [];")
lines.append("  Map<String, Map<int, _Slot>> _schedule = {};")
lines.append("  bool _isLoading = false;")
lines.append("  bool _isSaving = false;")
lines.append("  int _waitCount = 2;")
lines.append("  final List<String> _days = ['الاحد', 'الاثنين', 'الثلاثاء', 'الاربعاء', 'الخميس'];")
lines.append("  final int _periods = 7;")
lines.append("")
lines.append("  @override")
lines.append("  void initState() {")
lines.append("    super.initState();")
lines.append("    WidgetsBinding.instance.addPostFrameCallback((_) {")
lines.append("      final user = ref.read(authStateProvider).value;")
lines.append("      if (user != null) {")
lines.append("        setState(() => _schoolId = user.schoolId);")
lines.append("        _loadData();")
lines.append("      }")
lines.append("    });")
lines.append("  }")
lines.append("")

p.write_text(c + "\n".join(lines), encoding="utf-8")
print("class ok")
