import pathlib

p = pathlib.Path("lib/src/features/wait_management/presentation/wait_management_screen.dart")
c = p.read_text(encoding="utf-8")

lines = []
lines.append("  void _editSlot(String day, int period) {")
lines.append("    final slot = _schedule[day]?[period];")
lines.append("    final selected = List<String?>.filled(_waitCount, null);")
lines.append("    if (slot != null) {")
lines.append("      for (int i = 0; i < slot.teacherIds.length && i < _waitCount; i++)")
lines.append("        selected[i] = slot.teacherIds[i];")
lines.append("    }")
lines.append("    showDialog(")
lines.append("      context: context,")
lines.append("      builder: (_) => AlertDialog(")
lines.append("        backgroundColor: Colors.white,")
lines.append("        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),")
lines.append("        title: Text('تعديل: $day - الحصة $period',")
lines.append("            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15)),")
lines.append("        content: StatefulBuilder(builder: (ctx, setS) => SizedBox(")
lines.append("          width: 340,")
lines.append("          child: Column(mainAxisSize: MainAxisSize.min, children: [")
lines.append("            ...List.generate(_waitCount, (i) => Padding(")
lines.append("              padding: const EdgeInsets.only(bottom: 10),")
lines.append("              child: DropdownButtonFormField<String>(")
lines.append("                value: selected[i],")
lines.append("                decoration: InputDecoration(")
lines.append("                  labelText: 'منتظر ${i + 1}',")
lines.append("                  labelStyle: TextStyle(color: _wColors[i % _wColors.length]),")
lines.append("                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),")
lines.append("                  enabledBorder: OutlineInputBorder(")
lines.append("                    borderRadius: BorderRadius.circular(10),")
lines.append("                    borderSide: BorderSide(color: _wColors[i % _wColors.length].withOpacity(0.4))),")
lines.append("                  filled: true, fillColor: _wColors[i % _wColors.length].withOpacity(0.04),")
lines.append("                ),")
lines.append("                items: [")
lines.append("                  const DropdownMenuItem<String>(value: null, child: Text('-- فارغ --')),")
lines.append("                  ..._teachers.map((t) => DropdownMenuItem(")
lines.append("                    value: t['id'] as String,")
lines.append("                    child: Text(t['name'] as String, style: const TextStyle(fontSize: 13)))),")
lines.append("                ],")
lines.append("                onChanged: (v) => setS(() => selected[i] = v),")
lines.append("              ),")
lines.append("            )),")
lines.append("          ]),")
lines.append("        )),")
lines.append("        actions: [")
lines.append("          TextButton(onPressed: () => Navigator.pop(context),")
lines.append("              child: const Text('إلغاء', style: TextStyle(color: Colors.grey))),")
lines.append("          ElevatedButton(")
lines.append("            onPressed: () {")
lines.append("              Navigator.pop(context);")
lines.append("              setState(() {")
lines.append("                final ids = selected.where((s) => s != null).cast<String>().toList();")
lines.append("                final names = ids.map((id) {")
lines.append("                  final t = _teachers.firstWhere((t) => t['id'] == id, orElse: () => {'name': ''});")
lines.append("                  return t['name'] as String;")
lines.append("                }).toList();")
lines.append("                if (ids.isEmpty) {")
lines.append("                  _schedule[day]?.remove(period);")
lines.append("                } else {")
lines.append("                  _schedule.putIfAbsent(day, () => {});")
lines.append("                  _schedule[day]![period] = _Slot(")
lines.append("                    day: day, period: period,")
lines.append("                    teacherIds: ids, teacherNames: names, isManual: true);")
lines.append("                }")
lines.append("              });")
lines.append("            },")
lines.append("            style: ElevatedButton.styleFrom(")
lines.append("              backgroundColor: const Color(0xFF4F46E5), foregroundColor: Colors.white,")
lines.append("              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10))),")
lines.append("            child: const Text('حفظ'),")
lines.append("          ),")
lines.append("        ],")
lines.append("      ),")
lines.append("    );")
lines.append("  }")
lines.append("")

p.write_text(c + "\n".join(lines), encoding="utf-8")
print("editSlot ok")
