import pathlib

p = pathlib.Path("lib/src/features/wait_management/presentation/wait_management_screen.dart")
c = p.read_text(encoding="utf-8")

lines = []
lines.append("  // توليد تلقائي ذكي")
lines.append("  void _generateSchedule() {")
lines.append("    if (_teachers.isEmpty) return;")
lines.append("    _schedule = {};")
lines.append("    final assignedCount = <String, int>{};")
lines.append("    for (final t in _teachers) assignedCount[t['id'] as String] = 0;")
lines.append("")
lines.append("    final sorted = List<Map<String, dynamic>>.from(_teachers)")
lines.append("      ..sort((a, b) => (b['maxWeeklyClasses'] as int).compareTo(a['maxWeeklyClasses'] as int));")
lines.append("")
lines.append("    for (final day in _days) {")
lines.append("      _schedule[day] = {};")
lines.append("      for (int period = 1; period <= _periods; period++) {")
lines.append("        final usedToday = <String>{};")
lines.append("        for (final s in _schedule[day]!.values) usedToday.addAll(s.teacherIds);")
lines.append("")
lines.append("        final ids = <String>[];")
lines.append("        final names = <String>[];")
lines.append("")
lines.append("        for (int pos = 0; pos < _waitCount; pos++) {")
lines.append("          Map<String, dynamic>? chosen;")
lines.append("          int minCount = 9999;")
lines.append("          for (final t in sorted) {")
lines.append("            final tid = t['id'] as String;")
lines.append("            if (ids.contains(tid)) continue;")
lines.append("            if (pos == 0 && usedToday.contains(tid)) continue;")
lines.append("            final cnt = assignedCount[tid] ?? 0;")
lines.append("            if (cnt < minCount) { minCount = cnt; chosen = t; }")
lines.append("          }")
lines.append("          if (chosen == null) {")
lines.append("            for (final t in sorted) {")
lines.append("              final tid = t['id'] as String;")
lines.append("              if (ids.contains(tid)) continue;")
lines.append("              final cnt = assignedCount[tid] ?? 0;")
lines.append("              if (cnt < minCount) { minCount = cnt; chosen = t; }")
lines.append("            }")
lines.append("          }")
lines.append("          if (chosen != null) {")
lines.append("            final tid = chosen['id'] as String;")
lines.append("            ids.add(tid);")
lines.append("            names.add(chosen['name'] as String);")
lines.append("            assignedCount[tid] = (assignedCount[tid] ?? 0) + 1;")
lines.append("          }")
lines.append("        }")
lines.append("")
lines.append("        if (ids.isNotEmpty) {")
lines.append("          _schedule[day]![period] = _Slot(")
lines.append("            day: day, period: period,")
lines.append("            teacherIds: ids, teacherNames: names);")
lines.append("        }")
lines.append("      }")
lines.append("    }")
lines.append("  }")
lines.append("")
lines.append("  Future<void> _saveSchedule() async {")
lines.append("    if (_schoolId == null) return;")
lines.append("    setState(() => _isSaving = true);")
lines.append("    try {")
lines.append("      final slots = <Map<String, dynamic>>[]; ")
lines.append("      for (final day in _schedule.keys)")
lines.append("        for (final slot in _schedule[day]!.values) slots.add(slot.toMap());")
lines.append("      await FirebaseFirestore.instance")
lines.append("          .collection('Schools').doc(_schoolId)")
lines.append("          .collection('WaitSchedule').doc('current')")
lines.append("          .set({'slots': slots, 'waitCount': _waitCount, 'updatedAt': FieldValue.serverTimestamp()});")
lines.append("      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(")
lines.append("        content: Text('تم حفظ جدول الانتظار'),")
lines.append("        backgroundColor: Color(0xFF059669), behavior: SnackBarBehavior.floating));")
lines.append("    } catch (e) {")
lines.append("      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(")
lines.append("        content: Text('خطأ: $e'), backgroundColor: Colors.red));")
lines.append("    } finally { if (mounted) setState(() => _isSaving = false); }")
lines.append("  }")
lines.append("")

p.write_text(c + "\n".join(lines), encoding="utf-8")
print("generate+save ok")
