import pathlib

p = pathlib.Path("lib/src/features/wait_management/presentation/wait_management_screen.dart")
c = p.read_text(encoding="utf-8")

lines = []
lines.append("  Widget _buildBody() {")
lines.append("    return SingleChildScrollView(")
lines.append("      padding: const EdgeInsets.all(16),")
lines.append("      child: Column(children: [")
lines.append("        _buildLegend(),")
lines.append("        const SizedBox(height: 16),")
lines.append("        _buildGrid(),")
lines.append("        const SizedBox(height: 40),")
lines.append("      ]),")
lines.append("    );")
lines.append("  }")
lines.append("")
lines.append("  Widget _buildLegend() {")
lines.append("    return Container(")
lines.append("      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),")
lines.append("      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),")
lines.append("          border: Border.all(color: const Color(0xFFE2E8F0))),")
lines.append("      child: Row(children: [")
lines.append("        const Text('دليل الألوان:', style: TextStyle(color: Color(0xFF64748B), fontSize: 12, fontWeight: FontWeight.bold)),")
lines.append("        const SizedBox(width: 12),")
lines.append("        ...List.generate(_waitCount, (i) => Container(")
lines.append("          margin: const EdgeInsets.only(left: 10),")
lines.append("          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),")
lines.append("          decoration: BoxDecoration(")
lines.append("            color: _wColors[i % _wColors.length].withOpacity(0.1),")
lines.append("            borderRadius: BorderRadius.circular(20),")
lines.append("            border: Border.all(color: _wColors[i % _wColors.length].withOpacity(0.3))),")
lines.append("          child: Row(mainAxisSize: MainAxisSize.min, children: [")
lines.append("            Container(width: 8, height: 8, decoration: BoxDecoration(")
lines.append("              color: _wColors[i % _wColors.length], shape: BoxShape.circle)),")
lines.append("            const SizedBox(width: 5),")
lines.append("            Text('منتظر ${i + 1}', style: TextStyle(")
lines.append("              color: _wColors[i % _wColors.length], fontSize: 11, fontWeight: FontWeight.w600)),")
lines.append("          ]),")
lines.append("        )),")
lines.append("        const Spacer(),")
lines.append("        Container(")
lines.append("          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),")
lines.append("          decoration: BoxDecoration(color: const Color(0xFFFEF3C7), borderRadius: BorderRadius.circular(8)),")
lines.append("          child: const Row(mainAxisSize: MainAxisSize.min, children: [")
lines.append("            Icon(Icons.edit_rounded, size: 10, color: Color(0xFFD97706)),")
lines.append("            SizedBox(width: 4),")
lines.append("            Text('يدوي', style: TextStyle(color: Color(0xFFD97706), fontSize: 10)),")
lines.append("          ]),")
lines.append("        ),")
lines.append("      ]),")
lines.append("    );")
lines.append("  }")
lines.append("")
lines.append("  Widget _buildGrid() {")
lines.append("    final dayColors = [")
lines.append("      const Color(0xFF4F46E5), const Color(0xFF059669),")
lines.append("      const Color(0xFFD97706), const Color(0xFFDC2626), const Color(0xFF7C3AED),")
lines.append("    ];")
lines.append("    return Container(")
lines.append("      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(16),")
lines.append("          border: Border.all(color: const Color(0xFFE2E8F0)),")
lines.append("          boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 12)]),")
lines.append("      child: Column(children: [")
lines.append("        // Header row")
lines.append("        Container(")
lines.append("          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 10),")
lines.append("          decoration: const BoxDecoration(")
lines.append("            color: Color(0xFFF8FAFF),")
lines.append("            borderRadius: BorderRadius.vertical(top: Radius.circular(16)),")
lines.append("            border: Border(bottom: BorderSide(color: Color(0xFFE2E8F0)))),")
lines.append("          child: Row(children: [")
lines.append("            const SizedBox(width: 52, child: Text('الحصة', style: TextStyle(color: Color(0xFF64748B), fontSize: 11, fontWeight: FontWeight.bold), textAlign: TextAlign.center)),")
lines.append("            ...List.generate(_days.length, (i) => Expanded(child: Center(child: Container(")
lines.append("              padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 4),")
lines.append("              decoration: BoxDecoration(color: dayColors[i].withOpacity(0.1), borderRadius: BorderRadius.circular(8)),")
lines.append("              child: Text(_days[i], style: TextStyle(color: dayColors[i], fontSize: 11, fontWeight: FontWeight.bold)),")
lines.append("            )))),")
lines.append("          ]),")
lines.append("        ),")
lines.append("        // Data rows")
lines.append("        ...List.generate(_periods, (pi) {")
lines.append("          final period = pi + 1;")
lines.append("          return Container(")
lines.append("            decoration: BoxDecoration(")
lines.append("              color: pi % 2 == 0 ? Colors.white : const Color(0xFFFAFBFF),")
lines.append("              border: const Border(bottom: BorderSide(color: Color(0xFFE2E8F0), width: 0.5))),")
lines.append("            child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [")
lines.append("              Container(width: 52, padding: const EdgeInsets.symmetric(vertical: 8),")
lines.append("                decoration: const BoxDecoration(")
lines.append("                  color: Color(0xFFF1F5F9),")
lines.append("                  border: Border(right: BorderSide(color: Color(0xFFE2E8F0), width: 0.5))),")
lines.append("                child: Center(child: Column(mainAxisSize: MainAxisSize.min, children: [")
lines.append("                  Text('$period', style: const TextStyle(color: Color(0xFF4F46E5), fontSize: 16, fontWeight: FontWeight.bold)),")
lines.append("                  const Text('حصة', style: TextStyle(color: Color(0xFF94A3B8), fontSize: 9)),")
lines.append("                ]))),")
lines.append("              ...List.generate(_days.length, (di) {")
lines.append("                final day = _days[di];")
lines.append("                final slot = _schedule[day]?[period];")
lines.append("                return Expanded(child: GestureDetector(")
lines.append("                  onTap: () => _editSlot(day, period),")
lines.append("                  child: Container(")
lines.append("                    margin: const EdgeInsets.all(3),")
lines.append("                    padding: const EdgeInsets.all(4),")
lines.append("                    decoration: BoxDecoration(")
lines.append("                      color: slot != null ? const Color(0xFFF8FAFF) : const Color(0xFFF1F5F9),")
lines.append("                      borderRadius: BorderRadius.circular(8),")
lines.append("                      border: Border.all(color: slot != null ? const Color(0xFFCBD5E1) : const Color(0xFFE2E8F0))),")
lines.append("                    child: slot != null")
lines.append("                        ? Column(mainAxisSize: MainAxisSize.min, children: [")
lines.append("                            if (slot.isManual)")
lines.append("                              Container(margin: const EdgeInsets.only(bottom: 2),")
lines.append("                                padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 1),")
lines.append("                                decoration: BoxDecoration(color: const Color(0xFFFEF3C7), borderRadius: BorderRadius.circular(4)),")
lines.append("                                child: const Text('يدوي', style: TextStyle(color: Color(0xFFD97706), fontSize: 8, fontWeight: FontWeight.bold))),")
lines.append("                            ...List.generate(slot.teacherNames.length, (wi) => Container(")
lines.append("                              margin: const EdgeInsets.only(bottom: 2),")
lines.append("                              padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 3),")
lines.append("                              decoration: BoxDecoration(")
lines.append("                                color: _wColors[wi % _wColors.length].withOpacity(0.1),")
lines.append("                                borderRadius: BorderRadius.circular(5),")
lines.append("                                border: Border.all(color: _wColors[wi % _wColors.length].withOpacity(0.3))),")
lines.append("                              child: Text(_shortName(slot.teacherNames[wi]),")
lines.append("                                style: TextStyle(color: _wColors[wi % _wColors.length], fontSize: 9, fontWeight: FontWeight.w600),")
lines.append("                                maxLines: 1, overflow: TextOverflow.ellipsis),")
lines.append("                            )),")
lines.append("                          ])")
lines.append("                        : const Center(child: Icon(Icons.add_rounded, color: Color(0xFFCBD5E1), size: 16)),")
lines.append("                  ),")
lines.append("                ));")
lines.append("              }),")
lines.append("            ]),")
lines.append("          );")
lines.append("        }),")
lines.append("      ]),")
lines.append("    );")
lines.append("  }")
lines.append("")
lines.append("  String _shortName(String name) {")
lines.append("    final parts = name.trim().split(' ');")
lines.append("    return parts.length >= 2 ? '${parts[0]} ${parts[1]}' : name;")
lines.append("  }")
lines.append("}")

p.write_text(c + "\n".join(lines), encoding="utf-8")
print("grid+close ok")
