import pathlib

p = pathlib.Path("lib/src/features/wait_management/presentation/wait_management_screen.dart")

lines = []
lines.append("library;")
lines.append("")
lines.append("import 'package:flutter/material.dart';")
lines.append("import 'package:flutter_riverpod/flutter_riverpod.dart';")
lines.append("import 'package:cloud_firestore/cloud_firestore.dart';")
lines.append("import '../../auth/presentation/auth_controller.dart';")
lines.append("")
lines.append("// ألوان المنتظرين")
lines.append("const _wColors = [")
lines.append("  Color(0xFF4F46E5), // منتظر 1 - indigo")
lines.append("  Color(0xFF059669), // منتظر 2 - emerald")
lines.append("  Color(0xFFD97706), // منتظر 3 - amber")
lines.append("  Color(0xFFDC2626), // منتظر 4 - red")
lines.append("];")
lines.append("")
lines.append("class _Slot {")
lines.append("  final String day;")
lines.append("  final int period;")
lines.append("  List<String> teacherIds;")
lines.append("  List<String> teacherNames;")
lines.append("  bool isManual;")
lines.append("  _Slot({required this.day, required this.period,")
lines.append("    required this.teacherIds, required this.teacherNames, this.isManual = false});")
lines.append("  Map<String, dynamic> toMap() => {")
lines.append("    'day': day, 'period': period,")
lines.append("    'teacherIds': teacherIds, 'teacherNames': teacherNames,")
lines.append("    'isManual': isManual,")
lines.append("  };")
lines.append("}")
lines.append("")

p.write_text("\n".join(lines), encoding="utf-8")
print("header ok")
