import pathlib

p = pathlib.Path("lib/src/features/wait_management/presentation/wait_management_screen.dart")
c = p.read_text(encoding="utf-8")

lines = []
lines.append("  // استيراد من الجدول العام")
lines.append("  Future<void> _importFromGeneralSchedule() async {")
lines.append("    if (_schoolId == null) return;")
lines.append("    setState(() => _isLoading = true);")
lines.append("    try {")
lines.append("      final genSnap = await FirebaseFirestore.instance")
lines.append("          .collection('Schools').doc(_schoolId)")
lines.append("          .collection('GeneralSchedule')")
lines.append("          .orderBy('createdAt', descending: true).limit(1).get();")
lines.append("")
lines.append("      if (genSnap.docs.isEmpty) {")
lines.append("        _generateSchedule();")
lines.append("        if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(")
lines.append("          content: Text('لا يوجد جدول عام - تم التوليد التلقائي'),")
lines.append("          backgroundColor: Color(0xFFD97706)));")
lines.append("        return;")
lines.append("      }")
lines.append("")
lines.append("      final data = genSnap.docs.first.data();")
lines.append("      final teacherSchedules = data['teacherSchedules'] as Map<String, dynamic>? ?? {};")
lines.append("")
lines.append("      // استخراج حصص الانتظار من الجدول")
lines.append("      // حصة الانتظار = حصة فارغة في جدول المعلم (لا يوجد فصل)")
lines.append("      final waitByDayPeriod = <String, Map<int, List<String>>>{};")
lines.append("      final waitNamesByDayPeriod = <String, Map<int, List<String>>>{};")
lines.append("")
lines.append("      for (final entry in teacherSchedules.entries) {")
lines.append("        final teacherName = entry.key;")
lines.append("        final teacherLessons = entry.value;")
lines.append("        if (teacherLessons is! List) continue;")
lines.append("")
lines.append("        // ابحث عن حصص الانتظار (subject يحتوي 'منتظر' او 'انتظار')")
lines.append("        for (final lesson in teacherLessons) {")
lines.append("          if (lesson is! Map) continue;")
lines.append("          final subject = (lesson['subject'] ?? '').toString();")
lines.append("          final day = (lesson['dayName'] ?? lesson['day'] ?? '').toString();")
lines.append("          final period = lesson['period'] as int? ?? 0;")
lines.append("          if (subject.contains('منتظر') || subject.contains('انتظار') || subject.contains('نوبة')) {")
lines.append("            waitByDayPeriod.putIfAbsent(day, () => {});")
lines.append("            waitByDayPeriod[day]!.putIfAbsent(period, () => []);")
lines.append("            waitByDayPeriod[day]![period]!.add(teacherName);")
lines.append("            waitNamesByDayPeriod.putIfAbsent(day, () => {});")
lines.append("            waitNamesByDayPeriod[day]!.putIfAbsent(period, () => []);")
lines.append("            waitNamesByDayPeriod[day]![period]!.add(teacherName);")
lines.append("          }")
lines.append("        }")
lines.append("      }")
lines.append("")
lines.append("      if (waitByDayPeriod.isEmpty) {")
lines.append("        _generateSchedule();")
lines.append("        if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(")
lines.append("          content: Text('لا توجد حصص انتظار في الجدول - تم التوليد التلقائي'),")
lines.append("          backgroundColor: Color(0xFFD97706)));")
lines.append("        return;")
lines.append("      }")
lines.append("")
lines.append("      // بناء الجدول من البيانات المستوردة")
lines.append("      _schedule = {};")
lines.append("      for (final day in waitByDayPeriod.keys) {")
lines.append("        _schedule[day] = {};")
lines.append("        for (final period in waitByDayPeriod[day]!.keys) {")
lines.append("          final ids = waitByDayPeriod[day]![period]!;")
lines.append("          final names = waitNamesByDayPeriod[day]![period]!;")
lines.append("          _schedule[day]![period] = _Slot(")
lines.append("            day: day, period: period,")
lines.append("            teacherIds: ids.take(_waitCount).toList(),")
lines.append("            teacherNames: names.take(_waitCount).toList(),")
lines.append("          );")
lines.append("        }")
lines.append("      }")
lines.append("")
lines.append("      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(")
lines.append("        content: Text('تم استيراد جدول الانتظار من الجدول العام'),")
lines.append("        backgroundColor: Color(0xFF059669)));")
lines.append("    } catch (e) {")
lines.append("      _generateSchedule();")
lines.append("    } finally {")
lines.append("      if (mounted) setState(() => _isLoading = false);")
lines.append("    }")
lines.append("  }")
lines.append("")

p.write_text(c + "\n".join(lines), encoding="utf-8")
print("import ok")
