import pathlib

p = pathlib.Path("lib/src/features/wait_management/presentation/wait_management_screen.dart")
c = p.read_text(encoding="utf-8")

lines = []
lines.append("  Future<void> _loadData() async {")
lines.append("    if (_schoolId == null) return;")
lines.append("    setState(() => _isLoading = true);")
lines.append("    try {")
lines.append("      final ts = await FirebaseFirestore.instance")
lines.append("          .collection('Schools').doc(_schoolId).collection('Teachers').get();")
lines.append("      _teachers = ts.docs.map((d) {")
lines.append("        final data = d.data();")
lines.append("        return {'id': d.id, 'name': (data['name'] ?? '').toString(),")
lines.append("          'maxWeeklyClasses': (data['maxWeeklyClasses'] ?? 24) as int};")
lines.append("      }).where((t) => (t['name'] as String).isNotEmpty).toList();")
lines.append("")
lines.append("      final ws = await FirebaseFirestore.instance")
lines.append("          .collection('Schools').doc(_schoolId)")
lines.append("          .collection('WaitSchedule').doc('current').get();")
lines.append("      if (ws.exists) {")
lines.append("        final slots = (ws.data()?['slots'] as List?) ?? [];")
lines.append("        final wc = ws.data()?['waitCount'] as int? ?? 2;")
lines.append("        _waitCount = wc;")
lines.append("        _schedule = {};")
lines.append("        for (final s in slots) {")
lines.append("          final day = s['day'] as String;")
lines.append("          final period = s['period'] as int;")
lines.append("          _schedule.putIfAbsent(day, () => {});")
lines.append("          _schedule[day]![period] = _Slot(")
lines.append("            day: day, period: period,")
lines.append("            teacherIds: List<String>.from(s['teacherIds'] ?? []),")
lines.append("            teacherNames: List<String>.from(s['teacherNames'] ?? []),")
lines.append("            isManual: s['isManual'] == true,")
lines.append("          );")
lines.append("        }")
lines.append("      } else {")
lines.append("        _generateSchedule();")
lines.append("      }")
lines.append("    } catch (e) { debugPrint('wait load error: $e'); }")
lines.append("    finally { if (mounted) setState(() => _isLoading = false); }")
lines.append("  }")
lines.append("")

p.write_text(c + "\n".join(lines), encoding="utf-8")
print("loadData ok")
