import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../data/schedule_repository.dart';
import '../domain/schedule_slot.dart';
import '../../auth/presentation/auth_controller.dart';
import '../../admin/data/firestore_class_repository.dart';

final resolvedClassScheduleProvider =
    FutureProvider.family<List<ScheduleSlot>, String>((ref, classId) async {
  final user = ref.watch(authStateProvider).value;
  final schoolId = user?.schoolId ?? '';
  if (schoolId.isEmpty) return [];

  final classRepo = ref.watch(firestoreClassRepositoryProvider);
  final scheduleRepo = ref.watch(scheduleRepositoryProvider);

  // 1. Try to get the class details
  final classroom = await classRepo.getClassById(schoolId, classId);

  // Strategy A: Try by Name (Most likely if imported/generated by name)
  if (classroom != null) {
    final byName = await scheduleRepo.getClassSchedule(
      schoolId,
      classroom.name,
    );
    if (byName.isNotEmpty) return byName;
  }

  // Strategy B: Try by UUID (If generated internally using IDs)
  final byId = await scheduleRepo.getClassSchedule(schoolId, classId);
  if (byId.isNotEmpty) return byId;

  return [];
});

class StudentScheduleScreen extends ConsumerStatefulWidget {
  final String? classId;

  const StudentScheduleScreen({super.key, this.classId});

  @override
  ConsumerState<StudentScheduleScreen> createState() =>
      _StudentScheduleScreenState();
}

class _StudentScheduleScreenState extends ConsumerState<StudentScheduleScreen> {
  final ScrollController _horizontalController = ScrollController();
  Map<String, String> _subjectNameById = {};
  Map<String, String> _subjectIdByAlias = {};

  @override
  void initState() {
    super.initState();
    Future.microtask(() async {
      final user = ref.read(authStateProvider).value;
      final schoolId = user?.schoolId ?? '';
      if (schoolId.isEmpty) return;
      final data = await _loadSubjectCatalog(schoolId);
      if (!mounted) return;
      setState(() {
        _subjectNameById = data.$1;
        _subjectIdByAlias = data.$2;
      });
    });
  }

  String _normalizeKey(String s) {
    var v = s.trim().toLowerCase();
    v = v
        .replaceAll(RegExp(r'[\u064B-\u0652]'), '')
        .replaceAll('أ', 'ا')
        .replaceAll('إ', 'ا')
        .replaceAll('آ', 'ا')
        .replaceAll('ى', 'ي')
        .replaceAll('ة', 'ه')
        .replaceAll('ؤ', 'و')
        .replaceAll('ئ', 'ي')
        .replaceAll(RegExp(r'[^a-z0-9\u0600-\u06FF]+'), '');
    return v;
  }

  Future<(Map<String, String>, Map<String, String>)> _loadSubjectCatalog(
    String schoolId,
  ) async {
    final nameById = <String, String>{};
    final aliasLookup = <String, String>{};
    try {
      final doc = await FirebaseFirestore.instance
          .collection('Schools')
          .doc(schoolId)
          .collection('Config')
          .doc('Subjects')
          .get();
      final data = doc.data();
      final subjects = data?['subjects'];
      if (subjects is Map<String, dynamic>) {
        for (final entry in subjects.entries) {
          final id = entry.key.trim();
          if (id.isEmpty) continue;
          aliasLookup[_normalizeKey(id)] = id;
          final value = entry.value;
          if (value is Map<String, dynamic>) {
            final name = (value['name'] ?? id).toString().trim();
            nameById[id] = name.isEmpty ? id : name;
            if (name.isNotEmpty) {
              aliasLookup[_normalizeKey(name)] = id;
            }
            final rawAliases = value['aliases'];
            if (rawAliases is List) {
              for (final a in rawAliases) {
                if (a == null) continue;
                final s = a.toString().trim();
                if (s.isEmpty) continue;
                aliasLookup[_normalizeKey(s)] = id;
              }
            }
          } else {
            nameById[id] = id;
          }
        }
      }
    } catch (_) {}
    return (nameById, aliasLookup);
  }

  String _subjectLabel(String subject) {
    final s = subject.trim();
    if (s.isEmpty) return subject;
    final id = _subjectIdByAlias[_normalizeKey(s)] ?? s;
    final name = _subjectNameById[id];
    if (name != null && name.trim().isNotEmpty) return name;
    final lower = s.toLowerCase();
    if (lower == 'arabic') return 'اللغة العربية';
    if (lower == 'math') return 'الرياضيات';
    if (lower == 'science') return 'العلوم';
    if (lower == 'islamic') return 'التربية الإسلامية';
    if (lower == 'quran') return 'القرآن الكريم';
    if (lower == 'english') return 'اللغة الإنجليزية';
    if (lower == 'social') return 'الاجتماعيات';
    if (lower == 'computer' || lower == 'cs') return 'الحاسب الآلي';
    if (lower == 'pe') return 'التربية البدنية';
    if (lower == 'art') return 'التربية الفنية';
    return subject;
  }

  @override
  void dispose() {
    _horizontalController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    String? targetClassId = widget.classId;
    if (targetClassId != null && targetClassId.isEmpty) {
      targetClassId = null;
    }

    if (targetClassId == null) {
      final userAsync = ref.watch(authStateProvider);
      final user = userAsync.value;
      if (user != null &&
          user.assignedClassIds != null &&
          user.assignedClassIds!.isNotEmpty) {
        targetClassId = user.assignedClassIds!.first;
      }
    }

    if (targetClassId == null) {
      return const Scaffold(
        body: Center(child: Text('لم يتم العثور على فصل دراسي للطالب')),
      );
    }

    // Use the resolved provider which handles UUID -> Name conversion
    final scheduleAsync = ref.watch(
      resolvedClassScheduleProvider(targetClassId),
    );

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(title: const Text('جدولي الدراسي')),
      body: scheduleAsync.when(
        data: (slots) {
          if (slots.isEmpty) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(
                    Icons.calendar_today_outlined,
                    size: 64.sp,
                    color: Colors.grey,
                  ),
                  SizedBox(height: 16.h),
                  const Text('لا يوجد جدول معتمد'),
                ],
              ),
            );
          }

          // Group by Day
          final Map<String, List<ScheduleSlot>> grouped = {};
          final daysOrder = [
            'الأحد',
            'الاثنين',
            'الثلاثاء',
            'الأربعاء',
            'الخميس',
          ];

          for (var day in daysOrder) {
            grouped[day] = slots.where((s) => s.day == day).toList()
              ..sort((a, b) => a.period.compareTo(b.period));
          }

          final table = SingleChildScrollView(
            controller: _horizontalController,
            scrollDirection: Axis.horizontal,
            child: Table(
              defaultVerticalAlignment: TableCellVerticalAlignment.middle,
              columnWidths: {
                0: const FixedColumnWidth(100),
                for (int i = 1; i <= 7; i++) i: const FixedColumnWidth(140),
              },
              children: [
                TableRow(
                  decoration: BoxDecoration(color: Colors.grey.shade100),
                  children: [
                    Padding(
                      padding: EdgeInsets.all(8.w),
                      child: const Text(
                        'اليوم',
                        textAlign: TextAlign.center,
                        style: TextStyle(fontWeight: FontWeight.bold),
                      ),
                    ),
                    for (int p = 1; p <= 7; p++)
                      Padding(
                        padding: EdgeInsets.all(8.w),
                        child: Text(
                          'الحصة $p',
                          textAlign: TextAlign.center,
                          style: const TextStyle(fontWeight: FontWeight.bold),
                        ),
                      ),
                  ],
                ),
                ...daysOrder.map((day) {
                  final daySlots = grouped[day] ?? [];
                  return TableRow(
                    children: [
                      Padding(
                        padding: EdgeInsets.all(8.w),
                        child: Text(day, textAlign: TextAlign.center),
                      ),
                      ...List.generate(7, (index) {
                        final period = index + 1;
                        final slot = daySlots.firstWhere(
                          (s) => s.period == period,
                          orElse: () => ScheduleSlot(
                            day: day,
                            period: period,
                            className: '',
                            subject: '',
                          ),
                        );
                        final hasSubject = slot.subject.trim().isNotEmpty;
                        final subjectText = hasSubject
                            ? _subjectLabel(slot.subject)
                            : 'لا حصة';

                        final isVacant = !hasSubject;

                        return Padding(
                          padding: EdgeInsets.all(4.w),
                          child: Container(
                            height: 72.h,
                            decoration: BoxDecoration(
                              color: isVacant
                                  ? Colors.grey.shade100
                                  : Colors.white,
                              borderRadius: BorderRadius.circular(12.r),
                              border: Border.all(
                                color: isVacant
                                    ? Colors.red.shade200
                                    : Colors.grey.shade300,
                              ),
                            ),
                            padding: EdgeInsets.all(8.w),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Row(
                                  children: [
                                    Icon(
                                      isVacant
                                          ? Icons.block
                                          : Icons.check_circle,
                                      size: 16.sp,
                                      color: isVacant
                                          ? Colors.red.shade400
                                          : Colors.green.shade600,
                                    ),
                                    SizedBox(width: 4.w),
                                    Expanded(
                                      child: Text(
                                        subjectText,
                                        overflow: TextOverflow.ellipsis,
                                        style: TextStyle(
                                          fontSize: 13.sp,
                                          fontWeight: FontWeight.w600,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          ),
                        );
                      }),
                    ],
                  );
                }),
              ],
            ),
          );

          final tableWithScrollbar = RawScrollbar(
            controller: _horizontalController,
            thumbVisibility: true,
            trackVisibility: true,
            notificationPredicate: (_) => true,
            thickness: 8,
            radius: const Radius.circular(8),
            thumbColor: Colors.indigo,
            crossAxisMargin: 0,
            mainAxisMargin: 0,
            scrollbarOrientation: ScrollbarOrientation.bottom,
            child: table,
          );

          return SingleChildScrollView(
            padding: EdgeInsets.all(16.w),
            child: Card(
              elevation: 2,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12.r),
              ),
              child: Padding(
                padding: EdgeInsets.all(16.w),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Text(
                      'جدولي الدراسي',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 16.sp,
                        fontWeight: FontWeight.bold,
                        color: Colors.indigo.shade700,
                      ),
                    ),
                    SizedBox(height: 12.h),
                    tableWithScrollbar,
                  ],
                ),
              ),
            ),
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, s) => Center(child: Text('حدث خطأ: $e')),
      ),
    );
  }
}
